inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 8

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Style/BitwisePredicate:
  Enabled: false

Style/ComparableBetween:
  Enabled: false

Style/PartitionInsteadOfDoubleSelect:
  Enabled: false

Style/RedundantArgument:
  Enabled: false
