# frozen_string_literal: true

# Examples are sourced from the CommonMark 0.31.2 specification:
# https://spec.commonmark.org/0.31.2/

RSpec.describe "CommonMark compatibility" do
  PASSING_EXAMPLES = [
    {
      number: 43,
      section: "Thematic breaks",
      markdown: "***\n---\n___\n",
      html: "<hr />\n<hr />\n<hr />\n"
    },
    {
      number: 62,
      section: "ATX headings",
      markdown: "# foo\n## foo\n### foo\n#### foo\n##### foo\n###### foo\n",
      html: "<h1>foo</h1>\n<h2>foo</h2>\n<h3>foo</h3>\n<h4>foo</h4>\n<h5>foo</h5>\n<h6>foo</h6>\n"
    },
    {
      number: 142,
      section: "Fenced code blocks",
      markdown: "```ruby\ndef foo(x)\n  return 3\nend\n```\n",
      html: "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n"
    },
    {
      number: 228,
      section: "Block quotes",
      markdown: "> # Foo\n> bar\n> baz\n",
      html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n"
    },
    {
      number: 301,
      section: "Lists",
      markdown: "- foo\n- bar\n+ baz\n",
      html: "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<ul>\n<li>baz</li>\n</ul>\n"
    },
    {
      number: 277,
      section: "Lists",
      markdown: "-  foo\n\n   bar\n",
      html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n"
    },
    {
      number: 328,
      section: "Code spans",
      markdown: "`foo`\n",
      html: "<p><code>foo</code></p>\n"
    },
    {
      number: 329,
      section: "Code spans",
      markdown: "`` foo ` bar ``\n",
      html: "<p><code>foo ` bar</code></p>\n"
    },
    {
      number: 416,
      section: "Emphasis and strong emphasis",
      markdown: "foo***bar***baz\n",
      html: "<p>foo<em><strong>bar</strong></em>baz</p>\n"
    },
    {
      number: 418,
      section: "Emphasis and strong emphasis",
      markdown: "*foo **bar *baz* bim** bop*\n",
      html: "<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>\n"
    },
    {
      number: 482,
      section: "Inline links",
      markdown: "[link](/uri \"title\")\n",
      html: "<p><a href=\"/uri\" title=\"title\">link</a></p>\n"
    },
    {
      number: 594,
      section: "Autolinks",
      markdown: "<http://foo.bar.baz>\n",
      html: "<p><a href=\"http://foo.bar.baz\">http://foo.bar.baz</a></p>\n"
    },
    {
      number: 595,
      section: "Autolinks",
      markdown: "<https://foo.bar.baz/test?q=hello&id=22&boolean>\n",
      html: "<p><a href=\"https://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean\">https://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>\n"
    },
    {
      number: 193,
      section: "Link reference definitions",
      markdown: "   [foo]:\n      /url\n           'the title'\n[foo]\n",
      html: "<p><a href=\"/url\" title=\"the title\">foo</a></p>\n"
    },
    {
      number: 196,
      section: "Link reference definitions",
      markdown: "[foo]: /url '\ntitle\nline1\nline2\n'\n\n[foo]\n",
      html: "<p><a href=\"/url\" title=\"\ntitle\nline1\nline2\n\">foo</a></p>\n"
    },
    {
      number: 213,
      section: "Link reference definitions",
      markdown: "Foo\n[bar]: /baz\n\n[bar]\n",
      html: "<p>Foo\n[bar]: /baz</p>\n<p>[bar]</p>\n"
    },
    {
      number: 217,
      section: "Link reference definitions",
      markdown: "[foo]: /foo-url \"foo\"\n[bar]: /bar-url\n  \"bar\"\n[baz]: /baz-url\n\n[foo],\n[bar],\n[baz]\n",
      html: "<p><a href=\"/foo-url\" title=\"foo\">foo</a>,\n<a href=\"/bar-url\" title=\"bar\">bar</a>,\n<a href=\"/baz-url\">baz</a></p>\n"
    },
    {
      number: 218,
      section: "Link reference definitions",
      markdown: "[foo]\n\n> [foo]: /url\n",
      html: "<p><a href=\"/url\">foo</a></p>\n<blockquote>\n</blockquote>\n"
    },
    {
      number: 617,
      section: "Raw HTML",
      markdown: "Foo <responsive-image src=\"foo.jpg\" />\n",
      html: "<p>Foo <responsive-image src=\"foo.jpg\" /></p>\n"
    },
    {
      number: 618,
      section: "Raw HTML",
      markdown: "<33> <__>\n",
      html: "<p>&lt;33&gt; &lt;__&gt;</p>\n"
    },
    {
      number: 619,
      section: "Raw HTML",
      markdown: "<a h*#ref=\"hi\">\n",
      html: "<p>&lt;a h*#ref=&quot;hi&quot;&gt;</p>\n"
    },
    {
      number: 527,
      section: "Reference links",
      markdown: "[foo][bar]\n\n[bar]: /url \"title\"\n",
      html: "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"
    },
    {
      number: 566,
      section: "Reference links",
      markdown: "[foo][]\n\n[foo]: /url1\n",
      html: "<p><a href=\"/url1\">foo</a></p>\n"
    },
    {
      number: 588,
      section: "Reference images",
      markdown: "![foo]\n\n[foo]: /url \"title\"\n",
      html: "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"
    },
    {
      number: 572,
      section: "Images",
      markdown: "![foo](/url \"title\")\n",
      html: "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"
    },
    {
      number: 633,
      section: "Hard line breaks",
      markdown: "foo  \nbaz\n",
      html: "<p>foo<br />\nbaz</p>\n"
    },
    {
      number: 648,
      section: "Soft line breaks",
      markdown: "foo\nbaz\n",
      html: "<p>foo\nbaz</p>\n"
    },
    {
      number: 596,
      section: "Autolinks",
      markdown: "<foo@bar.example.com>\n",
      html: "<p><a href=\"mailto:foo@bar.example.com\">foo@bar.example.com</a></p>\n"
    },
    {
      number: 597,
      section: "Autolinks",
      markdown: "<foo+special@Bar.baz-bar0.com>\n",
      html: "<p><a href=\"mailto:foo+special@Bar.baz-bar0.com\">foo+special@Bar.baz-bar0.com</a></p>\n"
    },
    {
      number: 148,
      section: "HTML blocks",
      markdown: "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n\nokay.\n",
      html: "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n<p>okay.</p>\n"
    },
    {
      number: 149,
      section: "HTML blocks",
      markdown: "<pre>\n *foo*\n</pre>\n*bar*\n",
      html: "<pre>\n *foo*\n</pre>\n<p><em>bar</em></p>\n"
    },
    {
      number: 152,
      section: "HTML blocks",
      markdown: "<!-- foo -->\n\n    <!-- foo -->\n",
      html: "<!-- foo -->\n<pre><code>&lt;!-- foo --&gt;\n</code></pre>\n"
    },
    {
      number: 192,
      section: "Link reference definitions",
      markdown: "[foo]: /url \"title\"\n\n[foo]\n",
      html: "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"
    },
    {
      number: 206,
      section: "Link reference definitions",
      markdown: "[foo]\n\n[foo]: /url\n[foo]: /url2\n",
      html: "<p><a href=\"/url\">foo</a></p>\n"
    },
    {
      number: 207,
      section: "Link reference definitions",
      markdown: "[FOO]:\n   /url\n\n[Foo]\n",
      html: "<p><a href=\"/url\">Foo</a></p>\n"
    },
    {
      number: 209,
      section: "Link reference definitions",
      markdown: "[foo][]\n\n[foo]: /url \"title\"\n",
      html: "<p><a href=\"/url\" title=\"title\">foo</a></p>\n"
    },
    {
      number: 545,
      section: "Reference links",
      markdown: "[foo *bar*]\n\n[foo *bar*]: /url\n",
      html: "<p><a href=\"/url\">foo <em>bar</em></a></p>\n"
    },
    {
      number: 571,
      section: "Images",
      markdown: "![foo](/url \"title\")\n",
      html: "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"
    },
    {
      number: 589,
      section: "Reference images",
      markdown: "![foo]\n\n[foo]: /url \"title\"\n",
      html: "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n"
    },
    {
      number: 197,
      section: "Link reference definitions",
      markdown: "[foo]: /url\n\n[foo]\n",
      html: "<p><a href=\"/url\">foo</a></p>\n"
    },
    {
      number: 226,
      section: "Block quotes",
      markdown: "> [foo]: /url\n>\n> [foo]\n",
      html: "<blockquote>\n<p><a href=\"/url\">foo</a></p>\n</blockquote>\n"
    },
    {
      number: 89,
      section: "Indented code blocks",
      markdown: "    foo\n    bar\n",
      html: "<pre><code>foo\nbar\n</code></pre>\n"
    },
    {
      number: 98,
      section: "Fenced code blocks",
      markdown: "```ruby\ndef foo(x)\n  return 3\nend\n```\n",
      html: "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n"
    },
    {
      number: 105,
      section: "Fenced code blocks",
      markdown: "```ruby test\ncode\n```\n",
      html: "<pre><code class=\"language-ruby\">code\n</code></pre>\n"
    },
    { number: 3, section: "Tabs", markdown: "    a\ta\n    ὐ\ta\n", html: "<pre><code>a\ta\nὐ\ta\n</code></pre>\n" },
    { number: 10, section: "Tabs", markdown: "#\tFoo\n", html: "<h1>Foo</h1>\n" },
    { number: 11, section: "Tabs", markdown: "*\t*\t*\t\n", html: "<hr />\n" },
    { number: 13, section: "Backslash escapes", markdown: "\\\t\\A\\a\\ \\3\\φ\\«\n", html: "<p>\\\t\\A\\a\\ \\3\\φ\\«</p>\n" },
    { number: 14, section: "Backslash escapes", markdown: "\\*not emphasized*\n\\<br/> not a tag\n\\[not a link](/foo)\n\\`not code`\n1\\. not a list\n\\* not a list\n\\# not a heading\n\\[foo]: /url \"not a reference\"\n\\&ouml; not a character entity\n", html: "<p>*not emphasized*\n&lt;br/&gt; not a tag\n[not a link](/foo)\n`not code`\n1. not a list\n* not a list\n# not a heading\n[foo]: /url &quot;not a reference&quot;\n&amp;ouml; not a character entity</p>\n" },
    { number: 15, section: "Backslash escapes", markdown: "\\\\*emphasis*\n", html: "<p>\\<em>emphasis</em></p>\n" },
    { number: 16, section: "Backslash escapes", markdown: "foo\\\nbar\n", html: "<p>foo<br />\nbar</p>\n" },
    { number: 17, section: "Backslash escapes", markdown: "`` \\[\\` ``\n", html: "<p><code>\\[\\`</code></p>\n" },
    { number: 18, section: "Backslash escapes", markdown: "    \\[\\]\n", html: "<pre><code>\\[\\]\n</code></pre>\n" },
    { number: 19, section: "Backslash escapes", markdown: "~~~\n\\[\\]\n~~~\n", html: "<pre><code>\\[\\]\n</code></pre>\n" },
    { number: 21, section: "Backslash escapes", markdown: "<a href=\"/bar\\/)\">\n", html: "<a href=\"/bar\\/)\">\n" },
    { number: 26, section: "Entity and numeric character references", markdown: "&#35; &#1234; &#992; &#0;\n", html: "<p># Ӓ Ϡ �</p>\n" },
    { number: 27, section: "Entity and numeric character references", markdown: "&#X22; &#XD06; &#xcab;\n", html: "<p>&quot; ആ ಫ</p>\n" },
    { number: 28, section: "Entity and numeric character references", markdown: "&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;\n", html: "<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n&amp;#87654321;\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>\n" },
    { number: 29, section: "Entity and numeric character references", markdown: "&copy\n", html: "<p>&amp;copy</p>\n" },
    { number: 30, section: "Entity and numeric character references", markdown: "&MadeUpEntity;\n", html: "<p>&amp;MadeUpEntity;</p>\n" },
    { number: 31, section: "Entity and numeric character references", markdown: "<a href=\"&ouml;&ouml;.html\">\n", html: "<a href=\"&ouml;&ouml;.html\">\n" },
    { number: 35, section: "Entity and numeric character references", markdown: "`f&ouml;&ouml;`\n", html: "<p><code>f&amp;ouml;&amp;ouml;</code></p>\n" },
    { number: 36, section: "Entity and numeric character references", markdown: "    f&ouml;f&ouml;\n", html: "<pre><code>f&amp;ouml;f&amp;ouml;\n</code></pre>\n" },
    { number: 37, section: "Entity and numeric character references", markdown: "&#42;foo&#42;\n*foo*\n", html: "<p>*foo*\n<em>foo</em></p>\n" },
    { number: 38, section: "Entity and numeric character references", markdown: "&#42; foo\n\n* foo\n", html: "<p>* foo</p>\n<ul>\n<li>foo</li>\n</ul>\n" },
    { number: 39, section: "Entity and numeric character references", markdown: "foo&#10;&#10;bar\n", html: "<p>foo\n\nbar</p>\n" },
    { number: 40, section: "Entity and numeric character references", markdown: "&#9;foo\n", html: "<p>\tfoo</p>\n" },
    { number: 42, section: "Precedence", markdown: "- `one\n- two`\n", html: "<ul>\n<li>`one</li>\n<li>two`</li>\n</ul>\n" },
    { number: 44, section: "Thematic breaks", markdown: "+++\n", html: "<p>+++</p>\n" },
    { number: 45, section: "Thematic breaks", markdown: "===\n", html: "<p>===</p>\n" },
    { number: 46, section: "Thematic breaks", markdown: "--\n**\n__\n", html: "<p>--\n**\n__</p>\n" },
    { number: 47, section: "Thematic breaks", markdown: " ***\n  ***\n   ***\n", html: "<hr />\n<hr />\n<hr />\n" },
    { number: 50, section: "Thematic breaks", markdown: "_____________________________________\n", html: "<hr />\n" },
    { number: 51, section: "Thematic breaks", markdown: " - - -\n", html: "<hr />\n" },
    { number: 52, section: "Thematic breaks", markdown: " **  * ** * ** * **\n", html: "<hr />\n" },
    { number: 53, section: "Thematic breaks", markdown: "-     -      -      -\n", html: "<hr />\n" },
    { number: 54, section: "Thematic breaks", markdown: "- - - -    \n", html: "<hr />\n" },
    { number: 55, section: "Thematic breaks", markdown: "_ _ _ _ a\n\na------\n\n---a---\n", html: "<p>_ _ _ _ a</p>\n<p>a------</p>\n<p>---a---</p>\n" },
    { number: 57, section: "Thematic breaks", markdown: "- foo\n***\n- bar\n", html: "<ul>\n<li>foo</li>\n</ul>\n<hr />\n<ul>\n<li>bar</li>\n</ul>\n" },
    { number: 58, section: "Thematic breaks", markdown: "Foo\n***\nbar\n", html: "<p>Foo</p>\n<hr />\n<p>bar</p>\n" },
    { number: 63, section: "ATX headings", markdown: "####### foo\n", html: "<p>####### foo</p>\n" },
    { number: 64, section: "ATX headings", markdown: "#5 bolt\n\n#hashtag\n", html: "<p>#5 bolt</p>\n<p>#hashtag</p>\n" },
    { number: 65, section: "ATX headings", markdown: "\\## foo\n", html: "<p>## foo</p>\n" },
    { number: 66, section: "ATX headings", markdown: "# foo *bar* \\*baz\\*\n", html: "<h1>foo <em>bar</em> *baz*</h1>\n" },
    { number: 67, section: "ATX headings", markdown: "#                  foo                     \n", html: "<h1>foo</h1>\n" },
    { number: 68, section: "ATX headings", markdown: " ### foo\n  ## foo\n   # foo\n", html: "<h3>foo</h3>\n<h2>foo</h2>\n<h1>foo</h1>\n" },
    { number: 69, section: "ATX headings", markdown: "    # foo\n", html: "<pre><code># foo\n</code></pre>\n" },
    { number: 71, section: "ATX headings", markdown: "## foo ##\n  ###   bar    ###\n", html: "<h2>foo</h2>\n<h3>bar</h3>\n" },
    { number: 72, section: "ATX headings", markdown: "# foo ##################################\n##### foo ##\n", html: "<h1>foo</h1>\n<h5>foo</h5>\n" },
    { number: 73, section: "ATX headings", markdown: "### foo ###     \n", html: "<h3>foo</h3>\n" },
    { number: 74, section: "ATX headings", markdown: "### foo ### b\n", html: "<h3>foo ### b</h3>\n" },
    { number: 77, section: "ATX headings", markdown: "****\n## foo\n****\n", html: "<hr />\n<h2>foo</h2>\n<hr />\n" },
    { number: 78, section: "ATX headings", markdown: "Foo bar\n# baz\nBar foo\n", html: "<p>Foo bar</p>\n<h1>baz</h1>\n<p>Bar foo</p>\n" },
    { number: 85, section: "Setext headings", markdown: "    Foo\n    ---\n\n    Foo\n---\n", html: "<pre><code>Foo\n---\n\nFoo\n</code></pre>\n<hr />\n" },
    { number: 88, section: "Setext headings", markdown: "Foo\n= =\n\nFoo\n--- -\n", html: "<p>Foo\n= =</p>\n<p>Foo</p>\n<hr />\n" },
    { number: 92, section: "Setext headings", markdown: "> Foo\n---\n", html: "<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />\n" },
    { number: 94, section: "Setext headings", markdown: "- Foo\n---\n", html: "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n" },
    { number: 97, section: "Setext headings", markdown: "\n====\n", html: "<p>====</p>\n" },
    { number: 99, section: "Setext headings", markdown: "- foo\n-----\n", html: "<ul>\n<li>foo</li>\n</ul>\n<hr />\n" },
    { number: 100, section: "Setext headings", markdown: "    foo\n---\n", html: "<pre><code>foo\n</code></pre>\n<hr />\n" },
    { number: 101, section: "Setext headings", markdown: "> foo\n-----\n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n" },
    { number: 104, section: "Setext headings", markdown: "Foo\nbar\n\n---\n\nbaz\n", html: "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n" },
    { number: 106, section: "Setext headings", markdown: "Foo\nbar\n\\---\nbaz\n", html: "<p>Foo\nbar\n---\nbaz</p>\n" },
    { number: 107, section: "Indented code blocks", markdown: "    a simple\n      indented code block\n", html: "<pre><code>a simple\n  indented code block\n</code></pre>\n" },
    { number: 110, section: "Indented code blocks", markdown: "    <a/>\n    *hi*\n\n    - one\n", html: "<pre><code>&lt;a/&gt;\n*hi*\n\n- one\n</code></pre>\n" },
    { number: 111, section: "Indented code blocks", markdown: "    chunk1\n\n    chunk2\n  \n \n \n    chunk3\n", html: "<pre><code>chunk1\n\nchunk2\n\n\n\nchunk3\n</code></pre>\n" },
    { number: 114, section: "Indented code blocks", markdown: "    foo\nbar\n", html: "<pre><code>foo\n</code></pre>\n<p>bar</p>\n" },
    { number: 116, section: "Indented code blocks", markdown: "        foo\n    bar\n", html: "<pre><code>    foo\nbar\n</code></pre>\n" },
    { number: 118, section: "Indented code blocks", markdown: "    foo  \n", html: "<pre><code>foo  \n</code></pre>\n" },
    { number: 119, section: "Fenced code blocks", markdown: "```\n<\n >\n```\n", html: "<pre><code>&lt;\n &gt;\n</code></pre>\n" },
    { number: 120, section: "Fenced code blocks", markdown: "~~~\n<\n >\n~~~\n", html: "<pre><code>&lt;\n &gt;\n</code></pre>\n" },
    { number: 121, section: "Fenced code blocks", markdown: "``\nfoo\n``\n", html: "<p><code>foo</code></p>\n" },
    { number: 122, section: "Fenced code blocks", markdown: "```\naaa\n~~~\n```\n", html: "<pre><code>aaa\n~~~\n</code></pre>\n" },
    { number: 123, section: "Fenced code blocks", markdown: "~~~\naaa\n```\n~~~\n", html: "<pre><code>aaa\n```\n</code></pre>\n" },
    { number: 124, section: "Fenced code blocks", markdown: "````\naaa\n```\n``````\n", html: "<pre><code>aaa\n```\n</code></pre>\n" },
    { number: 125, section: "Fenced code blocks", markdown: "~~~~\naaa\n~~~\n~~~~\n", html: "<pre><code>aaa\n~~~\n</code></pre>\n" },
    { number: 126, section: "Fenced code blocks", markdown: "```\n", html: "<pre><code></code></pre>\n" },
    { number: 127, section: "Fenced code blocks", markdown: "`````\n\n```\naaa\n", html: "<pre><code>\n```\naaa\n</code></pre>\n" },
    { number: 129, section: "Fenced code blocks", markdown: "```\n\n  \n```\n", html: "<pre><code>\n  \n</code></pre>\n" },
    { number: 130, section: "Fenced code blocks", markdown: "```\n```\n", html: "<pre><code></code></pre>\n" },
    { number: 134, section: "Fenced code blocks", markdown: "    ```\n    aaa\n    ```\n", html: "<pre><code>```\naaa\n```\n</code></pre>\n" },
    { number: 135, section: "Fenced code blocks", markdown: "```\naaa\n  ```\n", html: "<pre><code>aaa\n</code></pre>\n" },
    { number: 136, section: "Fenced code blocks", markdown: "   ```\naaa\n  ```\n", html: "<pre><code>aaa\n</code></pre>\n" },
    { number: 137, section: "Fenced code blocks", markdown: "```\naaa\n    ```\n", html: "<pre><code>aaa\n    ```\n</code></pre>\n" },
    { number: 139, section: "Fenced code blocks", markdown: "~~~~~~\naaa\n~~~ ~~\n", html: "<pre><code>aaa\n~~~ ~~\n</code></pre>\n" },
    { number: 140, section: "Fenced code blocks", markdown: "foo\n```\nbar\n```\nbaz\n", html: "<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n" },
    { number: 143, section: "Fenced code blocks", markdown: "~~~~    ruby startline=3 $%@\#$\ndef foo(x)\n  return 3\nend\n~~~~~~~\n", html: "<pre><code class=\"language-ruby\">def foo(x)\n  return 3\nend\n</code></pre>\n" },
    { number: 144, section: "Fenced code blocks", markdown: "````;\n````\n", html: "<pre><code class=\"language-;\"></code></pre>\n" },
    { number: 146, section: "Fenced code blocks", markdown: "~~~ aa ``` ~~~\nfoo\n~~~\n", html: "<pre><code class=\"language-aa\">foo\n</code></pre>\n" },
    { number: 147, section: "Fenced code blocks", markdown: "```\n``` aaa\n```\n", html: "<pre><code>``` aaa\n</code></pre>\n" },
    { number: 150, section: "HTML blocks", markdown: " <div>\n  *hello*\n         <foo><a>\n", html: " <div>\n  *hello*\n         <foo><a>\n" },
    { number: 151, section: "HTML blocks", markdown: "</div>\n*foo*\n", html: "</div>\n*foo*\n" },
    { number: 155, section: "HTML blocks", markdown: "<div>\n*foo*\n\n*bar*\n", html: "<div>\n*foo*\n<p><em>bar</em></p>\n" },
    { number: 159, section: "HTML blocks", markdown: "<div><a href=\"bar\">*foo*</a></div>\n", html: "<div><a href=\"bar\">*foo*</a></div>\n" },
    { number: 161, section: "HTML blocks", markdown: "<div></div>\n``` c\nint x = 33;\n```\n", html: "<div></div>\n``` c\nint x = 33;\n```\n" },
    { number: 162, section: "HTML blocks", markdown: "<a href=\"foo\">\n*bar*\n</a>\n", html: "<a href=\"foo\">\n*bar*\n</a>\n" },
    { number: 163, section: "HTML blocks", markdown: "<Warning>\n*bar*\n</Warning>\n", html: "<Warning>\n*bar*\n</Warning>\n" },
    { number: 164, section: "HTML blocks", markdown: "<i class=\"foo\">\n*bar*\n</i>\n", html: "<i class=\"foo\">\n*bar*\n</i>\n" },
    { number: 165, section: "HTML blocks", markdown: "</ins>\n*bar*\n", html: "</ins>\n*bar*\n" },
    { number: 166, section: "HTML blocks", markdown: "<del>\n*foo*\n</del>\n", html: "<del>\n*foo*\n</del>\n" },
    { number: 167, section: "HTML blocks", markdown: "<del>\n\n*foo*\n\n</del>\n", html: "<del>\n<p><em>foo</em></p>\n</del>\n" },
    { number: 169, section: "HTML blocks", markdown: "<pre language=\"haskell\"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print $ parseTags tags\n</code></pre>\nokay\n", html: "<pre language=\"haskell\"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print $ parseTags tags\n</code></pre>\n<p>okay</p>\n" },
    { number: 170, section: "HTML blocks", markdown: "<script type=\"text/javascript\">\n// JavaScript example\n\ndocument.getElementById(\"demo\").innerHTML = \"Hello JavaScript!\";\n</script>\nokay\n", html: "<script type=\"text/javascript\">\n// JavaScript example\n\ndocument.getElementById(\"demo\").innerHTML = \"Hello JavaScript!\";\n</script>\n<p>okay</p>\n" },
    { number: 171, section: "HTML blocks", markdown: "<textarea>\n\n*foo*\n\n_bar_\n\n</textarea>\n", html: "<textarea>\n\n*foo*\n\n_bar_\n\n</textarea>\n" },
    { number: 172, section: "HTML blocks", markdown: "<style\n  type=\"text/css\">\nh1 {color:red;}\n\np {color:blue;}\n</style>\nokay\n", html: "<style\n  type=\"text/css\">\nh1 {color:red;}\n\np {color:blue;}\n</style>\n<p>okay</p>\n" },
    { number: 173, section: "HTML blocks", markdown: "<style\n  type=\"text/css\">\n\nfoo\n", html: "<style\n  type=\"text/css\">\n\nfoo\n" },
    { number: 174, section: "HTML blocks", markdown: "> <div>\n> foo\n\nbar\n", html: "<blockquote>\n<div>\nfoo\n</blockquote>\n<p>bar</p>\n" },
    { number: 176, section: "HTML blocks", markdown: "<style>p{color:red;}</style>\n*foo*\n", html: "<style>p{color:red;}</style>\n<p><em>foo</em></p>\n" },
    { number: 177, section: "HTML blocks", markdown: "<!-- foo -->*bar*\n*baz*\n", html: "<!-- foo -->*bar*\n<p><em>baz</em></p>\n" },
    { number: 178, section: "HTML blocks", markdown: "<script>\nfoo\n</script>1. *bar*\n", html: "<script>\nfoo\n</script>1. *bar*\n" },
    { number: 179, section: "HTML blocks", markdown: "<!-- Foo\n\nbar\n   baz -->\nokay\n", html: "<!-- Foo\n\nbar\n   baz -->\n<p>okay</p>\n" },
    { number: 180, section: "HTML blocks", markdown: "<?php\n\n  echo '>';\n\n?>\nokay\n", html: "<?php\n\n  echo '>';\n\n?>\n<p>okay</p>\n" },
    { number: 181, section: "HTML blocks", markdown: "<!DOCTYPE html>\n", html: "<!DOCTYPE html>\n" },
    { number: 183, section: "HTML blocks", markdown: "  <!-- foo -->\n\n    <!-- foo -->\n", html: "  <!-- foo -->\n<pre><code>&lt;!-- foo --&gt;\n</code></pre>\n" },
    { number: 184, section: "HTML blocks", markdown: "  <div>\n\n    <div>\n", html: "  <div>\n<pre><code>&lt;div&gt;\n</code></pre>\n" },
    { number: 185, section: "HTML blocks", markdown: "Foo\n<div>\nbar\n</div>\n", html: "<p>Foo</p>\n<div>\nbar\n</div>\n" },
    { number: 186, section: "HTML blocks", markdown: "<div>\nbar\n</div>\n*foo*\n", html: "<div>\nbar\n</div>\n*foo*\n" },
    { number: 188, section: "HTML blocks", markdown: "<div>\n\n*Emphasized* text.\n\n</div>\n", html: "<div>\n<p><em>Emphasized</em> text.</p>\n</div>\n" },
    { number: 189, section: "HTML blocks", markdown: "<div>\n*Emphasized* text.\n</div>\n", html: "<div>\n*Emphasized* text.\n</div>\n" },
    { number: 190, section: "HTML blocks", markdown: "<table>\n\n<tr>\n\n<td>\nHi\n</td>\n\n</tr>\n\n</table>\n", html: "<table>\n<tr>\n<td>\nHi\n</td>\n</tr>\n</table>\n" },
    { number: 191, section: "HTML blocks", markdown: "<table>\n\n  <tr>\n\n    <td>\n      Hi\n    </td>\n\n  </tr>\n\n</table>\n", html: "<table>\n  <tr>\n<pre><code>&lt;td&gt;\n  Hi\n&lt;/td&gt;\n</code></pre>\n  </tr>\n</table>\n" },
    { number: 198, section: "Link reference definitions", markdown: "[foo]:\n/url\n\n[foo]\n", html: "<p><a href=\"/url\">foo</a></p>\n" },
    { number: 199, section: "Link reference definitions", markdown: "[foo]:\n\n[foo]\n", html: "<p>[foo]:</p>\n<p>[foo]</p>\n" },
    { number: 200, section: "Link reference definitions", markdown: "[foo]: <>\n\n[foo]\n", html: "<p><a href=\"\">foo</a></p>\n" },
    { number: 203, section: "Link reference definitions", markdown: "[foo]\n\n[foo]: url\n", html: "<p><a href=\"url\">foo</a></p>\n" },
    { number: 204, section: "Link reference definitions", markdown: "[foo]\n\n[foo]: first\n[foo]: second\n", html: "<p><a href=\"first\">foo</a></p>\n" },
    { number: 205, section: "Link reference definitions", markdown: "[FOO]: /url\n\n[Foo]\n", html: "<p><a href=\"/url\">Foo</a></p>\n" },
    { number: 211, section: "Link reference definitions", markdown: "    [foo]: /url \"title\"\n\n[foo]\n", html: "<pre><code>[foo]: /url &quot;title&quot;\n</code></pre>\n<p>[foo]</p>\n" },
    { number: 212, section: "Link reference definitions", markdown: "```\n[foo]: /url\n```\n\n[foo]\n", html: "<pre><code>[foo]: /url\n</code></pre>\n<p>[foo]</p>\n" },
    { number: 214, section: "Link reference definitions", markdown: "# [Foo]\n[foo]: /url\n> bar\n", html: "<h1><a href=\"/url\">Foo</a></h1>\n<blockquote>\n<p>bar</p>\n</blockquote>\n" },
    { number: 216, section: "Link reference definitions", markdown: "[foo]: /url\n===\n[foo]\n", html: "<p>===\n<a href=\"/url\">foo</a></p>\n" },
    { number: 219, section: "Paragraphs", markdown: "aaa\n\nbbb\n", html: "<p>aaa</p>\n<p>bbb</p>\n" },
    { number: 220, section: "Paragraphs", markdown: "aaa\nbbb\n\nccc\nddd\n", html: "<p>aaa\nbbb</p>\n<p>ccc\nddd</p>\n" },
    { number: 221, section: "Paragraphs", markdown: "aaa\n\n\nbbb\n", html: "<p>aaa</p>\n<p>bbb</p>\n" },
    { number: 225, section: "Paragraphs", markdown: "    aaa\nbbb\n", html: "<pre><code>aaa\n</code></pre>\n<p>bbb</p>\n" },
    { number: 227, section: "Blank lines", markdown: "  \n\naaa\n  \n\n# aaa\n\n  \n", html: "<p>aaa</p>\n<h1>aaa</h1>\n" },
    { number: 229, section: "Block quotes", markdown: "># Foo\n>bar\n> baz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n" },
    { number: 230, section: "Block quotes", markdown: "   > # Foo\n   > bar\n > baz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n" },
    { number: 231, section: "Block quotes", markdown: "    > # Foo\n    > bar\n    > baz\n", html: "<pre><code>&gt; # Foo\n&gt; bar\n&gt; baz\n</code></pre>\n" },
    { number: 234, section: "Block quotes", markdown: "> foo\n---\n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n" },
    { number: 235, section: "Block quotes", markdown: "> - foo\n- bar\n", html: "<blockquote>\n<ul>\n<li>foo</li>\n</ul>\n</blockquote>\n<ul>\n<li>bar</li>\n</ul>\n" },
    { number: 236, section: "Block quotes", markdown: ">     foo\n    bar\n", html: "<blockquote>\n<pre><code>foo\n</code></pre>\n</blockquote>\n<pre><code>bar\n</code></pre>\n" },
    { number: 237, section: "Block quotes", markdown: "> ```\nfoo\n```\n", html: "<blockquote>\n<pre><code></code></pre>\n</blockquote>\n<p>foo</p>\n<pre><code></code></pre>\n" },
    { number: 239, section: "Block quotes", markdown: ">\n", html: "<blockquote>\n</blockquote>\n" },
    { number: 240, section: "Block quotes", markdown: ">\n>  \n> \n", html: "<blockquote>\n</blockquote>\n" },
    { number: 241, section: "Block quotes", markdown: ">\n> foo\n>  \n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n" },
    { number: 243, section: "Block quotes", markdown: "> foo\n> bar\n", html: "<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n" },
    { number: 244, section: "Block quotes", markdown: "> foo\n>\n> bar\n", html: "<blockquote>\n<p>foo</p>\n<p>bar</p>\n</blockquote>\n" },
    { number: 245, section: "Block quotes", markdown: "foo\n> bar\n", html: "<p>foo</p>\n<blockquote>\n<p>bar</p>\n</blockquote>\n" },
    { number: 246, section: "Block quotes", markdown: "> aaa\n***\n> bbb\n", html: "<blockquote>\n<p>aaa</p>\n</blockquote>\n<hr />\n<blockquote>\n<p>bbb</p>\n</blockquote>\n" },
    { number: 248, section: "Block quotes", markdown: "> bar\n\nbaz\n", html: "<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n" },
    { number: 249, section: "Block quotes", markdown: "> bar\n>\nbaz\n", html: "<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n" },
    { number: 253, section: "List items", markdown: "A paragraph\nwith two lines.\n\n    indented code\n\n> A block quote.\n", html: "<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n" },
    { number: 256, section: "List items", markdown: "- one\n\n  two\n", html: "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n" },
    { number: 257, section: "List items", markdown: " -    one\n\n     two\n", html: "<ul>\n<li>one</li>\n</ul>\n<pre><code> two\n</code></pre>\n" },
    { number: 260, section: "List items", markdown: ">>- one\n>>\n  >  > two\n", html: "<blockquote>\n<blockquote>\n<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n</blockquote>\n</blockquote>\n" },
    { number: 261, section: "List items", markdown: "-one\n\n2.two\n", html: "<p>-one</p>\n<p>2.two</p>\n" },
    { number: 265, section: "List items", markdown: "123456789. ok\n", html: "<ol start=\"123456789\">\n<li>ok</li>\n</ol>\n" },
    { number: 268, section: "List items", markdown: "003. ok\n", html: "<ol start=\"3\">\n<li>ok</li>\n</ol>\n" },
    { number: 269, section: "List items", markdown: "-1. not ok\n", html: "<p>-1. not ok</p>\n" },
    { number: 272, section: "List items", markdown: "    indented code\n\nparagraph\n\n    more code\n", html: "<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n" },
    { number: 285, section: "List items", markdown: "foo\n*\n\nfoo\n1.\n", html: "<p>foo\n*</p>\n<p>foo\n1.</p>\n" },
    { number: 289, section: "List items", markdown: "    1.  A paragraph\n        with two lines.\n\n            indented code\n\n        > A block quote.\n", html: "<pre><code>1.  A paragraph\n    with two lines.\n\n        indented code\n\n    &gt; A block quote.\n</code></pre>\n" },
    { number: 291, section: "List items", markdown: "  1.  A paragraph\n    with two lines.\n", html: "<ol>\n<li>A paragraph\nwith two lines.</li>\n</ol>\n" },
    { number: 295, section: "List items", markdown: "- foo\n - bar\n  - baz\n   - boo\n", html: "<ul>\n<li>foo</li>\n<li>bar</li>\n<li>baz</li>\n<li>boo</li>\n</ul>\n" },
    { number: 297, section: "List items", markdown: "10) foo\n   - bar\n", html: "<ol start=\"10\">\n<li>foo</li>\n</ol>\n<ul>\n<li>bar</li>\n</ul>\n" },
    { number: 302, section: "Lists", markdown: "1. foo\n2. bar\n3) baz\n", html: "<ol>\n<li>foo</li>\n<li>bar</li>\n</ol>\n<ol start=\"3\">\n<li>baz</li>\n</ol>\n" },
    { number: 303, section: "Lists", markdown: "Foo\n- bar\n- baz\n", html: "<p>Foo</p>\n<ul>\n<li>bar</li>\n<li>baz</li>\n</ul>\n" },
    { number: 305, section: "Lists", markdown: "The number of windows in my house is\n1.  The number of doors is 6.\n", html: "<p>The number of windows in my house is</p>\n<ol>\n<li>The number of doors is 6.</li>\n</ol>\n" },
    { number: 306, section: "Lists", markdown: "- foo\n\n- bar\n\n\n- baz\n", html: "<ul>\n<li>\n<p>foo</p>\n</li>\n<li>\n<p>bar</p>\n</li>\n<li>\n<p>baz</p>\n</li>\n</ul>\n" },
    { number: 308, section: "Lists", markdown: "- foo\n- bar\n\n<!-- -->\n\n- baz\n- bim\n", html: "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<!-- -->\n<ul>\n<li>baz</li>\n<li>bim</li>\n</ul>\n" },
    { number: 310, section: "Lists", markdown: "- a\n - b\n  - c\n   - d\n  - e\n - f\n- g\n", html: "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n<li>e</li>\n<li>f</li>\n<li>g</li>\n</ul>\n" },
    { number: 311, section: "Lists", markdown: "1. a\n\n  2. b\n\n   3. c\n", html: "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ol>\n" },
    { number: 313, section: "Lists", markdown: "1. a\n\n  2. b\n\n    3. c\n", html: "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n</ol>\n<pre><code>3. c\n</code></pre>\n" },
    { number: 314, section: "Lists", markdown: "- a\n- b\n\n- c\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ul>\n" },
    { number: 316, section: "Lists", markdown: "- a\n- b\n\n  c\n- d\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n" },
    { number: 317, section: "Lists", markdown: "- a\n- b\n\n  [ref]: /url\n- d\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n" },
    { number: 322, section: "Lists", markdown: "- a\n", html: "<ul>\n<li>a</li>\n</ul>\n" },
    { number: 324, section: "Lists", markdown: "1. ```\n   foo\n   ```\n\n   bar\n", html: "<ol>\n<li>\n<pre><code>foo\n</code></pre>\n<p>bar</p>\n</li>\n</ol>\n" },
    { number: 327, section: "Inlines", markdown: "`hi`lo`\n", html: "<p><code>hi</code>lo`</p>\n" },
    { number: 330, section: "Code spans", markdown: "` `` `\n", html: "<p><code>``</code></p>\n" },
    { number: 331, section: "Code spans", markdown: "`  ``  `\n", html: "<p><code> `` </code></p>\n" },
    { number: 332, section: "Code spans", markdown: "` a`\n", html: "<p><code> a</code></p>\n" },
    { number: 333, section: "Code spans", markdown: "` b `\n", html: "<p><code> b </code></p>\n" },
    { number: 334, section: "Code spans", markdown: "` `\n`  `\n", html: "<p><code> </code>\n<code>  </code></p>\n" },
    { number: 335, section: "Code spans", markdown: "``\nfoo\nbar  \nbaz\n``\n", html: "<p><code>foo bar   baz</code></p>\n" },
    { number: 336, section: "Code spans", markdown: "``\nfoo \n``\n", html: "<p><code>foo </code></p>\n" },
    { number: 337, section: "Code spans", markdown: "`foo   bar \nbaz`\n", html: "<p><code>foo   bar  baz</code></p>\n" },
    { number: 339, section: "Code spans", markdown: "``foo`bar``\n", html: "<p><code>foo`bar</code></p>\n" },
    { number: 340, section: "Code spans", markdown: "` foo `` bar `\n", html: "<p><code>foo `` bar</code></p>\n" },
    { number: 341, section: "Code spans", markdown: "*foo`*`\n", html: "<p>*foo<code>*</code></p>\n" },
    { number: 342, section: "Code spans", markdown: "[not a `link](/foo`)\n", html: "<p>[not a <code>link](/foo</code>)</p>\n" },
    { number: 344, section: "Code spans", markdown: "<a href=\"`\">`\n", html: "<p><a href=\"`\">`</p>\n" },
    { number: 348, section: "Code spans", markdown: "`foo\n", html: "<p>`foo</p>\n" },
    { number: 349, section: "Code spans", markdown: "`foo``bar``\n", html: "<p>`foo<code>bar</code></p>\n" },
    { number: 350, section: "Emphasis and strong emphasis", markdown: "*foo bar*\n", html: "<p><em>foo bar</em></p>\n" },
    { number: 351, section: "Emphasis and strong emphasis", markdown: "a * foo bar*\n", html: "<p>a * foo bar*</p>\n" },
    { number: 352, section: "Emphasis and strong emphasis", markdown: "a*\"foo\"*\n", html: "<p>a*&quot;foo&quot;*</p>\n" },
    { number: 353, section: "Emphasis and strong emphasis", markdown: "* a *\n", html: "<p>* a *</p>\n" },
    { number: 355, section: "Emphasis and strong emphasis", markdown: "foo*bar*\n", html: "<p>foo<em>bar</em></p>\n" },
    { number: 356, section: "Emphasis and strong emphasis", markdown: "5*6*78\n", html: "<p>5<em>6</em>78</p>\n" },
    { number: 357, section: "Emphasis and strong emphasis", markdown: "_foo bar_\n", html: "<p><em>foo bar</em></p>\n" },
    { number: 358, section: "Emphasis and strong emphasis", markdown: "_ foo bar_\n", html: "<p>_ foo bar_</p>\n" },
    { number: 359, section: "Emphasis and strong emphasis", markdown: "a_\"foo\"_\n", html: "<p>a_&quot;foo&quot;_</p>\n" },
    { number: 360, section: "Emphasis and strong emphasis", markdown: "foo_bar_\n", html: "<p>foo_bar_</p>\n" },
    { number: 361, section: "Emphasis and strong emphasis", markdown: "5_6_78\n", html: "<p>5_6_78</p>\n" },
    { number: 362, section: "Emphasis and strong emphasis", markdown: "пристаням_стремятся_\n", html: "<p>пристаням_стремятся_</p>\n" },
    { number: 363, section: "Emphasis and strong emphasis", markdown: "aa_\"bb\"_cc\n", html: "<p>aa_&quot;bb&quot;_cc</p>\n" },
    { number: 364, section: "Emphasis and strong emphasis", markdown: "foo-_(bar)_\n", html: "<p>foo-<em>(bar)</em></p>\n" },
    { number: 365, section: "Emphasis and strong emphasis", markdown: "_foo*\n", html: "<p>_foo*</p>\n" },
    { number: 366, section: "Emphasis and strong emphasis", markdown: "*foo bar *\n", html: "<p>*foo bar *</p>\n" },
    { number: 367, section: "Emphasis and strong emphasis", markdown: "*foo bar\n*\n", html: "<p>*foo bar\n*</p>\n" },
    { number: 368, section: "Emphasis and strong emphasis", markdown: "*(*foo)\n", html: "<p>*(*foo)</p>\n" },
    { number: 369, section: "Emphasis and strong emphasis", markdown: "*(*foo*)*\n", html: "<p><em>(<em>foo</em>)</em></p>\n" },
    { number: 370, section: "Emphasis and strong emphasis", markdown: "*foo*bar\n", html: "<p><em>foo</em>bar</p>\n" },
    { number: 371, section: "Emphasis and strong emphasis", markdown: "_foo bar _\n", html: "<p>_foo bar _</p>\n" },
    { number: 372, section: "Emphasis and strong emphasis", markdown: "_(_foo)\n", html: "<p>_(_foo)</p>\n" },
    { number: 373, section: "Emphasis and strong emphasis", markdown: "_(_foo_)_\n", html: "<p><em>(<em>foo</em>)</em></p>\n" },
    { number: 374, section: "Emphasis and strong emphasis", markdown: "_foo_bar\n", html: "<p>_foo_bar</p>\n" },
    { number: 375, section: "Emphasis and strong emphasis", markdown: "_пристаням_стремятся\n", html: "<p>_пристаням_стремятся</p>\n" },
    { number: 376, section: "Emphasis and strong emphasis", markdown: "_foo_bar_baz_\n", html: "<p><em>foo_bar_baz</em></p>\n" },
    { number: 377, section: "Emphasis and strong emphasis", markdown: "_(bar)_.\n", html: "<p><em>(bar)</em>.</p>\n" },
    { number: 378, section: "Emphasis and strong emphasis", markdown: "**foo bar**\n", html: "<p><strong>foo bar</strong></p>\n" },
    { number: 379, section: "Emphasis and strong emphasis", markdown: "** foo bar**\n", html: "<p>** foo bar**</p>\n" },
    { number: 380, section: "Emphasis and strong emphasis", markdown: "a**\"foo\"**\n", html: "<p>a**&quot;foo&quot;**</p>\n" },
    { number: 381, section: "Emphasis and strong emphasis", markdown: "foo**bar**\n", html: "<p>foo<strong>bar</strong></p>\n" },
    { number: 382, section: "Emphasis and strong emphasis", markdown: "__foo bar__\n", html: "<p><strong>foo bar</strong></p>\n" },
    { number: 383, section: "Emphasis and strong emphasis", markdown: "__ foo bar__\n", html: "<p>__ foo bar__</p>\n" },
    { number: 384, section: "Emphasis and strong emphasis", markdown: "__\nfoo bar__\n", html: "<p>__\nfoo bar__</p>\n" },
    { number: 385, section: "Emphasis and strong emphasis", markdown: "a__\"foo\"__\n", html: "<p>a__&quot;foo&quot;__</p>\n" },
    { number: 386, section: "Emphasis and strong emphasis", markdown: "foo__bar__\n", html: "<p>foo__bar__</p>\n" },
    { number: 387, section: "Emphasis and strong emphasis", markdown: "5__6__78\n", html: "<p>5__6__78</p>\n" },
    { number: 388, section: "Emphasis and strong emphasis", markdown: "пристаням__стремятся__\n", html: "<p>пристаням__стремятся__</p>\n" },
    { number: 389, section: "Emphasis and strong emphasis", markdown: "__foo, __bar__, baz__\n", html: "<p><strong>foo, <strong>bar</strong>, baz</strong></p>\n" },
    { number: 390, section: "Emphasis and strong emphasis", markdown: "foo-__(bar)__\n", html: "<p>foo-<strong>(bar)</strong></p>\n" },
    { number: 391, section: "Emphasis and strong emphasis", markdown: "**foo bar **\n", html: "<p>**foo bar **</p>\n" },
    { number: 392, section: "Emphasis and strong emphasis", markdown: "**(**foo)\n", html: "<p>**(**foo)</p>\n" },
    { number: 393, section: "Emphasis and strong emphasis", markdown: "*(**foo**)*\n", html: "<p><em>(<strong>foo</strong>)</em></p>\n" },
    { number: 394, section: "Emphasis and strong emphasis", markdown: "**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n", html: "<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>\n" },
    { number: 395, section: "Emphasis and strong emphasis", markdown: "**foo \"*bar*\" foo**\n", html: "<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>\n" },
    { number: 396, section: "Emphasis and strong emphasis", markdown: "**foo**bar\n", html: "<p><strong>foo</strong>bar</p>\n" },
    { number: 397, section: "Emphasis and strong emphasis", markdown: "__foo bar __\n", html: "<p>__foo bar __</p>\n" },
    { number: 398, section: "Emphasis and strong emphasis", markdown: "__(__foo)\n", html: "<p>__(__foo)</p>\n" },
    { number: 399, section: "Emphasis and strong emphasis", markdown: "_(__foo__)_\n", html: "<p><em>(<strong>foo</strong>)</em></p>\n" },
    { number: 400, section: "Emphasis and strong emphasis", markdown: "__foo__bar\n", html: "<p>__foo__bar</p>\n" },
    { number: 401, section: "Emphasis and strong emphasis", markdown: "__пристаням__стремятся\n", html: "<p>__пристаням__стремятся</p>\n" },
    { number: 402, section: "Emphasis and strong emphasis", markdown: "__foo__bar__baz__\n", html: "<p><strong>foo__bar__baz</strong></p>\n" },
    { number: 403, section: "Emphasis and strong emphasis", markdown: "__(bar)__.\n", html: "<p><strong>(bar)</strong>.</p>\n" },
    { number: 404, section: "Emphasis and strong emphasis", markdown: "*foo [bar](/url)*\n", html: "<p><em>foo <a href=\"/url\">bar</a></em></p>\n" },
    { number: 405, section: "Emphasis and strong emphasis", markdown: "*foo\nbar*\n", html: "<p><em>foo\nbar</em></p>\n" },
    { number: 406, section: "Emphasis and strong emphasis", markdown: "_foo __bar__ baz_\n", html: "<p><em>foo <strong>bar</strong> baz</em></p>\n" },
    { number: 407, section: "Emphasis and strong emphasis", markdown: "_foo _bar_ baz_\n", html: "<p><em>foo <em>bar</em> baz</em></p>\n" },
    { number: 408, section: "Emphasis and strong emphasis", markdown: "__foo_ bar_\n", html: "<p><em><em>foo</em> bar</em></p>\n" },
    { number: 409, section: "Emphasis and strong emphasis", markdown: "*foo *bar**\n", html: "<p><em>foo <em>bar</em></em></p>\n" },
    { number: 410, section: "Emphasis and strong emphasis", markdown: "*foo **bar** baz*\n", html: "<p><em>foo <strong>bar</strong> baz</em></p>\n" },
    { number: 413, section: "Emphasis and strong emphasis", markdown: "***foo** bar*\n", html: "<p><em><strong>foo</strong> bar</em></p>\n" },
    { number: 414, section: "Emphasis and strong emphasis", markdown: "*foo **bar***\n", html: "<p><em>foo <strong>bar</strong></em></p>\n" },
    { number: 417, section: "Emphasis and strong emphasis", markdown: "foo******bar*********baz\n", html: "<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>\n" },
    { number: 419, section: "Emphasis and strong emphasis", markdown: "*foo [*bar*](/url)*\n", html: "<p><em>foo <a href=\"/url\"><em>bar</em></a></em></p>\n" },
    { number: 420, section: "Emphasis and strong emphasis", markdown: "** is not an empty emphasis\n", html: "<p>** is not an empty emphasis</p>\n" },
    { number: 421, section: "Emphasis and strong emphasis", markdown: "**** is not an empty strong emphasis\n", html: "<p>**** is not an empty strong emphasis</p>\n" },
    { number: 422, section: "Emphasis and strong emphasis", markdown: "**foo [bar](/url)**\n", html: "<p><strong>foo <a href=\"/url\">bar</a></strong></p>\n" },
    { number: 423, section: "Emphasis and strong emphasis", markdown: "**foo\nbar**\n", html: "<p><strong>foo\nbar</strong></p>\n" },
    { number: 424, section: "Emphasis and strong emphasis", markdown: "__foo _bar_ baz__\n", html: "<p><strong>foo <em>bar</em> baz</strong></p>\n" },
    { number: 425, section: "Emphasis and strong emphasis", markdown: "__foo __bar__ baz__\n", html: "<p><strong>foo <strong>bar</strong> baz</strong></p>\n" },
    { number: 426, section: "Emphasis and strong emphasis", markdown: "____foo__ bar__\n", html: "<p><strong><strong>foo</strong> bar</strong></p>\n" },
    { number: 427, section: "Emphasis and strong emphasis", markdown: "**foo **bar****\n", html: "<p><strong>foo <strong>bar</strong></strong></p>\n" },
    { number: 428, section: "Emphasis and strong emphasis", markdown: "**foo *bar* baz**\n", html: "<p><strong>foo <em>bar</em> baz</strong></p>\n" },
    { number: 430, section: "Emphasis and strong emphasis", markdown: "***foo* bar**\n", html: "<p><strong><em>foo</em> bar</strong></p>\n" },
    { number: 431, section: "Emphasis and strong emphasis", markdown: "**foo *bar***\n", html: "<p><strong>foo <em>bar</em></strong></p>\n" },
    { number: 432, section: "Emphasis and strong emphasis", markdown: "**foo *bar **baz**\nbim* bop**\n", html: "<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>\n" },
    { number: 433, section: "Emphasis and strong emphasis", markdown: "**foo [*bar*](/url)**\n", html: "<p><strong>foo <a href=\"/url\"><em>bar</em></a></strong></p>\n" },
    { number: 434, section: "Emphasis and strong emphasis", markdown: "__ is not an empty emphasis\n", html: "<p>__ is not an empty emphasis</p>\n" },
    { number: 435, section: "Emphasis and strong emphasis", markdown: "____ is not an empty strong emphasis\n", html: "<p>____ is not an empty strong emphasis</p>\n" },
    { number: 436, section: "Emphasis and strong emphasis", markdown: "foo ***\n", html: "<p>foo ***</p>\n" },
    { number: 437, section: "Emphasis and strong emphasis", markdown: "foo *\\**\n", html: "<p>foo <em>*</em></p>\n" },
    { number: 438, section: "Emphasis and strong emphasis", markdown: "foo *_*\n", html: "<p>foo <em>_</em></p>\n" },
    { number: 439, section: "Emphasis and strong emphasis", markdown: "foo *****\n", html: "<p>foo *****</p>\n" },
    { number: 440, section: "Emphasis and strong emphasis", markdown: "foo **\\***\n", html: "<p>foo <strong>*</strong></p>\n" },
    { number: 441, section: "Emphasis and strong emphasis", markdown: "foo **_**\n", html: "<p>foo <strong>_</strong></p>\n" },
    { number: 442, section: "Emphasis and strong emphasis", markdown: "**foo*\n", html: "<p>*<em>foo</em></p>\n" },
    { number: 443, section: "Emphasis and strong emphasis", markdown: "*foo**\n", html: "<p><em>foo</em>*</p>\n" },
    { number: 444, section: "Emphasis and strong emphasis", markdown: "***foo**\n", html: "<p>*<strong>foo</strong></p>\n" },
    { number: 445, section: "Emphasis and strong emphasis", markdown: "****foo*\n", html: "<p>***<em>foo</em></p>\n" },
    { number: 446, section: "Emphasis and strong emphasis", markdown: "**foo***\n", html: "<p><strong>foo</strong>*</p>\n" },
    { number: 447, section: "Emphasis and strong emphasis", markdown: "*foo****\n", html: "<p><em>foo</em>***</p>\n" },
    { number: 448, section: "Emphasis and strong emphasis", markdown: "foo ___\n", html: "<p>foo ___</p>\n" },
    { number: 449, section: "Emphasis and strong emphasis", markdown: "foo _\\__\n", html: "<p>foo <em>_</em></p>\n" },
    { number: 450, section: "Emphasis and strong emphasis", markdown: "foo _*_\n", html: "<p>foo <em>*</em></p>\n" },
    { number: 451, section: "Emphasis and strong emphasis", markdown: "foo _____\n", html: "<p>foo _____</p>\n" },
    { number: 452, section: "Emphasis and strong emphasis", markdown: "foo __\\___\n", html: "<p>foo <strong>_</strong></p>\n" },
    { number: 453, section: "Emphasis and strong emphasis", markdown: "foo __*__\n", html: "<p>foo <strong>*</strong></p>\n" },
    { number: 454, section: "Emphasis and strong emphasis", markdown: "__foo_\n", html: "<p>_<em>foo</em></p>\n" },
    { number: 455, section: "Emphasis and strong emphasis", markdown: "_foo__\n", html: "<p><em>foo</em>_</p>\n" },
    { number: 456, section: "Emphasis and strong emphasis", markdown: "___foo__\n", html: "<p>_<strong>foo</strong></p>\n" },
    { number: 457, section: "Emphasis and strong emphasis", markdown: "____foo_\n", html: "<p>___<em>foo</em></p>\n" },
    { number: 458, section: "Emphasis and strong emphasis", markdown: "__foo___\n", html: "<p><strong>foo</strong>_</p>\n" },
    { number: 459, section: "Emphasis and strong emphasis", markdown: "_foo____\n", html: "<p><em>foo</em>___</p>\n" },
    { number: 460, section: "Emphasis and strong emphasis", markdown: "**foo**\n", html: "<p><strong>foo</strong></p>\n" },
    { number: 461, section: "Emphasis and strong emphasis", markdown: "*_foo_*\n", html: "<p><em><em>foo</em></em></p>\n" },
    { number: 462, section: "Emphasis and strong emphasis", markdown: "__foo__\n", html: "<p><strong>foo</strong></p>\n" },
    { number: 463, section: "Emphasis and strong emphasis", markdown: "_*foo*_\n", html: "<p><em><em>foo</em></em></p>\n" },
    { number: 464, section: "Emphasis and strong emphasis", markdown: "****foo****\n", html: "<p><strong><strong>foo</strong></strong></p>\n" },
    { number: 465, section: "Emphasis and strong emphasis", markdown: "____foo____\n", html: "<p><strong><strong>foo</strong></strong></p>\n" },
    { number: 466, section: "Emphasis and strong emphasis", markdown: "******foo******\n", html: "<p><strong><strong><strong>foo</strong></strong></strong></p>\n" },
    { number: 467, section: "Emphasis and strong emphasis", markdown: "***foo***\n", html: "<p><em><strong>foo</strong></em></p>\n" },
    { number: 468, section: "Emphasis and strong emphasis", markdown: "_____foo_____\n", html: "<p><em><strong><strong>foo</strong></strong></em></p>\n" },
    { number: 469, section: "Emphasis and strong emphasis", markdown: "*foo _bar* baz_\n", html: "<p><em>foo _bar</em> baz_</p>\n" },
    { number: 470, section: "Emphasis and strong emphasis", markdown: "*foo __bar *baz bim__ bam*\n", html: "<p><em>foo <strong>bar *baz bim</strong> bam</em></p>\n" },
    { number: 471, section: "Emphasis and strong emphasis", markdown: "**foo **bar baz**\n", html: "<p>**foo <strong>bar baz</strong></p>\n" },
    { number: 472, section: "Emphasis and strong emphasis", markdown: "*foo *bar baz*\n", html: "<p>*foo <em>bar baz</em></p>\n" },
    { number: 473, section: "Emphasis and strong emphasis", markdown: "*[bar*](/url)\n", html: "<p>*<a href=\"/url\">bar*</a></p>\n" },
    { number: 474, section: "Emphasis and strong emphasis", markdown: "_foo [bar_](/url)\n", html: "<p>_foo <a href=\"/url\">bar_</a></p>\n" },
    { number: 475, section: "Emphasis and strong emphasis", markdown: "*<img src=\"foo\" title=\"*\"/>\n", html: "<p>*<img src=\"foo\" title=\"*\"/></p>\n" },
    { number: 476, section: "Emphasis and strong emphasis", markdown: "**<a href=\"**\">\n", html: "<p>**<a href=\"**\"></p>\n" },
    { number: 477, section: "Emphasis and strong emphasis", markdown: "__<a href=\"__\">\n", html: "<p>__<a href=\"__\"></p>\n" },
    { number: 478, section: "Emphasis and strong emphasis", markdown: "*a `*`*\n", html: "<p><em>a <code>*</code></em></p>\n" },
    { number: 479, section: "Emphasis and strong emphasis", markdown: "_a `_`_\n", html: "<p><em>a <code>_</code></em></p>\n" },
    { number: 480, section: "Emphasis and strong emphasis", markdown: "**a<https://foo.bar/?q=**>\n", html: "<p>**a<a href=\"https://foo.bar/?q=**\">https://foo.bar/?q=**</a></p>\n" },
    { number: 481, section: "Emphasis and strong emphasis", markdown: "__a<https://foo.bar/?q=__>\n", html: "<p>__a<a href=\"https://foo.bar/?q=__\">https://foo.bar/?q=__</a></p>\n" },
    { number: 483, section: "Links", markdown: "[link](/uri)\n", html: "<p><a href=\"/uri\">link</a></p>\n" },
    { number: 484, section: "Links", markdown: "[](./target.md)\n", html: "<p><a href=\"./target.md\"></a></p>\n" },
    { number: 490, section: "Links", markdown: "[link](foo\nbar)\n", html: "<p>[link](foo\nbar)</p>\n" },
    { number: 491, section: "Links", markdown: "[link](<foo\nbar>)\n", html: "<p>[link](<foo\nbar>)</p>\n" },
    { number: 496, section: "Links", markdown: "[link](foo(and(bar)))\n", html: "<p><a href=\"foo(and(bar))\">link</a></p>\n" },
    { number: 497, section: "Links", markdown: "[link](foo(and(bar))\n", html: "<p>[link](foo(and(bar))</p>\n" },
    { number: 501, section: "Links", markdown: "[link](#fragment)\n\n[link](https://example.com#fragment)\n\n[link](https://example.com?foo=3#frag)\n", html: "<p><a href=\"#fragment\">link</a></p>\n<p><a href=\"https://example.com#fragment\">link</a></p>\n<p><a href=\"https://example.com?foo=3#frag\">link</a></p>\n" },
    { number: 511, section: "Links", markdown: "[link] (/uri)\n", html: "<p>[link] (/uri)</p>\n" },
    { number: 512, section: "Links", markdown: "[link [foo [bar]]](/uri)\n", html: "<p><a href=\"/uri\">link [foo [bar]]</a></p>\n" },
    { number: 513, section: "Links", markdown: "[link] bar](/uri)\n", html: "<p>[link] bar](/uri)</p>\n" },
    { number: 514, section: "Links", markdown: "[link [bar](/uri)\n", html: "<p>[link <a href=\"/uri\">bar</a></p>\n" },
    { number: 515, section: "Links", markdown: "[link \\[bar](/uri)\n", html: "<p><a href=\"/uri\">link [bar</a></p>\n" },
    { number: 516, section: "Links", markdown: "[link *foo **bar** `#`*](/uri)\n", html: "<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n" },
    { number: 517, section: "Links", markdown: "[![moon](moon.jpg)](/uri)\n", html: "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>\n" },
    { number: 518, section: "Links", markdown: "[foo [bar](/uri)](/uri)\n", html: "<p>[foo <a href=\"/uri\">bar</a>](/uri)</p>\n" },
    { number: 519, section: "Links", markdown: "[foo *[bar [baz](/uri)](/uri)*](/uri)\n", html: "<p>[foo <em>[bar <a href=\"/uri\">baz</a>](/uri)</em>](/uri)</p>\n" },
    { number: 521, section: "Links", markdown: "*[foo*](/uri)\n", html: "<p>*<a href=\"/uri\">foo*</a></p>\n" },
    { number: 522, section: "Links", markdown: "[foo *bar](baz*)\n", html: "<p><a href=\"baz*\">foo *bar</a></p>\n" },
    { number: 523, section: "Links", markdown: "*foo [bar* baz]\n", html: "<p><em>foo [bar</em> baz]</p>\n" },
    { number: 524, section: "Links", markdown: "[foo <bar attr=\"](baz)\">\n", html: "<p>[foo <bar attr=\"](baz)\"></p>\n" },
    { number: 525, section: "Links", markdown: "[foo`](/uri)`\n", html: "<p>[foo<code>](/uri)</code></p>\n" },
    { number: 528, section: "Links", markdown: "[link [foo [bar]]][ref]\n\n[ref]: /uri\n", html: "<p><a href=\"/uri\">link [foo [bar]]</a></p>\n" },
    { number: 529, section: "Links", markdown: "[link \\[bar][ref]\n\n[ref]: /uri\n", html: "<p><a href=\"/uri\">link [bar</a></p>\n" },
    { number: 530, section: "Links", markdown: "[link *foo **bar** `#`*][ref]\n\n[ref]: /uri\n", html: "<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n" },
    { number: 531, section: "Links", markdown: "[![moon](moon.jpg)][ref]\n\n[ref]: /uri\n", html: "<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>\n" },
    { number: 532, section: "Links", markdown: "[foo [bar](/uri)][ref]\n\n[ref]: /uri\n", html: "<p>[foo <a href=\"/uri\">bar</a>]<a href=\"/uri\">ref</a></p>\n" },
    { number: 533, section: "Links", markdown: "[foo *bar [baz][ref]*][ref]\n\n[ref]: /uri\n", html: "<p>[foo <em>bar <a href=\"/uri\">baz</a></em>]<a href=\"/uri\">ref</a></p>\n" },
    { number: 534, section: "Links", markdown: "*[foo*][ref]\n\n[ref]: /uri\n", html: "<p>*<a href=\"/uri\">foo*</a></p>\n" },
    { number: 535, section: "Links", markdown: "[foo *bar][ref]*\n\n[ref]: /uri\n", html: "<p><a href=\"/uri\">foo *bar</a>*</p>\n" },
    { number: 536, section: "Links", markdown: "[foo <bar attr=\"][ref]\">\n\n[ref]: /uri\n", html: "<p>[foo <bar attr=\"][ref]\"></p>\n" },
    { number: 537, section: "Links", markdown: "[foo`][ref]`\n\n[ref]: /uri\n", html: "<p>[foo<code>][ref]</code></p>\n" },
    { number: 539, section: "Links", markdown: "[foo][BaR]\n\n[bar]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\">foo</a></p>\n" },
    { number: 542, section: "Links", markdown: "[foo] [bar]\n\n[bar]: /url \"title\"\n", html: "<p>[foo] <a href=\"/url\" title=\"title\">bar</a></p>\n" },
    { number: 543, section: "Links", markdown: "[foo]\n[bar]\n\n[bar]: /url \"title\"\n", html: "<p>[foo]\n<a href=\"/url\" title=\"title\">bar</a></p>\n" },
    { number: 544, section: "Links", markdown: "[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]\n", html: "<p><a href=\"/url1\">bar</a></p>\n" },
    { number: 547, section: "Links", markdown: "[foo][ref[bar]]\n\n[ref[bar]]: /uri\n", html: "<p>[foo][ref[bar]]</p>\n<p>[ref[bar]]: /uri</p>\n" },
    { number: 548, section: "Links", markdown: "[[[foo]]]\n\n[[[foo]]]: /url\n", html: "<p>[[[foo]]]</p>\n<p>[[[foo]]]: /url</p>\n" },
    { number: 549, section: "Links", markdown: "[foo][ref\\[]\n\n[ref\\[]: /uri\n", html: "<p><a href=\"/uri\">foo</a></p>\n" },
    { number: 550, section: "Links", markdown: "[bar\\\\]: /uri\n\n[bar\\\\]\n", html: "<p><a href=\"/uri\">bar\\</a></p>\n" },
    { number: 551, section: "Links", markdown: "[]\n\n[]: /uri\n", html: "<p>[]</p>\n<p>[]: /uri</p>\n" },
    { number: 553, section: "Links", markdown: "[foo][]\n\n[foo]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\">foo</a></p>\n" },
    { number: 554, section: "Links", markdown: "[*foo* bar][]\n\n[*foo* bar]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>\n" },
    { number: 555, section: "Links", markdown: "[Foo][]\n\n[foo]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\">Foo</a></p>\n" },
    { number: 557, section: "Links", markdown: "[foo]\n\n[foo]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\">foo</a></p>\n" },
    { number: 558, section: "Links", markdown: "[*foo* bar]\n\n[*foo* bar]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\"><em>foo</em> bar</a></p>\n" },
    { number: 559, section: "Links", markdown: "[[*foo* bar]]\n\n[*foo* bar]: /url \"title\"\n", html: "<p>[<a href=\"/url\" title=\"title\"><em>foo</em> bar</a>]</p>\n" },
    { number: 560, section: "Links", markdown: "[[bar [foo]\n\n[foo]: /url\n", html: "<p>[[bar <a href=\"/url\">foo</a></p>\n" },
    { number: 561, section: "Links", markdown: "[Foo]\n\n[foo]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\">Foo</a></p>\n" },
    { number: 562, section: "Links", markdown: "[foo] bar\n\n[foo]: /url\n", html: "<p><a href=\"/url\">foo</a> bar</p>\n" },
    { number: 563, section: "Links", markdown: "\\[foo]\n\n[foo]: /url \"title\"\n", html: "<p>[foo]</p>\n" },
    { number: 564, section: "Links", markdown: "[foo*]: /url\n\n*[foo*]\n", html: "<p>*<a href=\"/url\">foo*</a></p>\n" },
    { number: 565, section: "Links", markdown: "[foo][bar]\n\n[foo]: /url1\n[bar]: /url2\n", html: "<p><a href=\"/url2\">foo</a></p>\n" },
    { number: 569, section: "Links", markdown: "[foo][bar][baz]\n\n[baz]: /url\n", html: "<p>[foo]<a href=\"/url\">bar</a></p>\n" },
    { number: 570, section: "Links", markdown: "[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2\n", html: "<p><a href=\"/url2\">foo</a><a href=\"/url1\">baz</a></p>\n" },
    { number: 573, section: "Images", markdown: "![foo *bar*]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n", html: "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n" },
    { number: 574, section: "Images", markdown: "![foo ![bar](/url)](/url2)\n", html: "<p><img src=\"/url2\" alt=\"foo bar\" /></p>\n" },
    { number: 575, section: "Images", markdown: "![foo [bar](/url)](/url2)\n", html: "<p><img src=\"/url2\" alt=\"foo bar\" /></p>\n" },
    { number: 576, section: "Images", markdown: "![foo *bar*][]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n", html: "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n" },
    { number: 577, section: "Images", markdown: "![foo *bar*][foobar]\n\n[FOOBAR]: train.jpg \"train & tracks\"\n", html: "<p><img src=\"train.jpg\" alt=\"foo bar\" title=\"train &amp; tracks\" /></p>\n" },
    { number: 578, section: "Images", markdown: "![foo](train.jpg)\n", html: "<p><img src=\"train.jpg\" alt=\"foo\" /></p>\n" },
    { number: 581, section: "Images", markdown: "![](/url)\n", html: "<p><img src=\"/url\" alt=\"\" /></p>\n" },
    { number: 582, section: "Images", markdown: "![foo][bar]\n\n[bar]: /url\n", html: "<p><img src=\"/url\" alt=\"foo\" /></p>\n" },
    { number: 583, section: "Images", markdown: "![foo][bar]\n\n[BAR]: /url\n", html: "<p><img src=\"/url\" alt=\"foo\" /></p>\n" },
    { number: 584, section: "Images", markdown: "![foo][]\n\n[foo]: /url \"title\"\n", html: "<p><img src=\"/url\" alt=\"foo\" title=\"title\" /></p>\n" },
    { number: 585, section: "Images", markdown: "![*foo* bar][]\n\n[*foo* bar]: /url \"title\"\n", html: "<p><img src=\"/url\" alt=\"foo bar\" title=\"title\" /></p>\n" },
    { number: 586, section: "Images", markdown: "![Foo][]\n\n[foo]: /url \"title\"\n", html: "<p><img src=\"/url\" alt=\"Foo\" title=\"title\" /></p>\n" },
    { number: 590, section: "Images", markdown: "![[foo]]\n\n[[foo]]: /url \"title\"\n", html: "<p>![[foo]]</p>\n<p>[[foo]]: /url &quot;title&quot;</p>\n" },
    { number: 591, section: "Images", markdown: "![Foo]\n\n[foo]: /url \"title\"\n", html: "<p><img src=\"/url\" alt=\"Foo\" title=\"title\" /></p>\n" },
    { number: 592, section: "Images", markdown: "!\\[foo]\n\n[foo]: /url \"title\"\n", html: "<p>![foo]</p>\n" },
    { number: 593, section: "Images", markdown: "\\![foo]\n\n[foo]: /url \"title\"\n", html: "<p>!<a href=\"/url\" title=\"title\">foo</a></p>\n" },
    { number: 598, section: "Autolinks", markdown: "<a+b+c:d>\n", html: "<p><a href=\"a+b+c:d\">a+b+c:d</a></p>\n" },
    { number: 599, section: "Autolinks", markdown: "<made-up-scheme://foo,bar>\n", html: "<p><a href=\"made-up-scheme://foo,bar\">made-up-scheme://foo,bar</a></p>\n" },
    { number: 600, section: "Autolinks", markdown: "<https://../>\n", html: "<p><a href=\"https://../\">https://../</a></p>\n" },
    { number: 601, section: "Autolinks", markdown: "<localhost:5001/foo>\n", html: "<p><a href=\"localhost:5001/foo\">localhost:5001/foo</a></p>\n" },
    { number: 602, section: "Autolinks", markdown: "<https://foo.bar/baz bim>\n", html: "<p>&lt;https://foo.bar/baz bim&gt;</p>\n" },
    { number: 604, section: "Autolinks", markdown: "<foo@bar.example.com>\n", html: "<p><a href=\"mailto:foo@bar.example.com\">foo@bar.example.com</a></p>\n" },
    { number: 605, section: "Autolinks", markdown: "<foo+special@Bar.baz-bar0.com>\n", html: "<p><a href=\"mailto:foo+special@Bar.baz-bar0.com\">foo+special@Bar.baz-bar0.com</a></p>\n" },
    { number: 606, section: "Autolinks", markdown: "<foo\\+@bar.example.com>\n", html: "<p>&lt;foo+@bar.example.com&gt;</p>\n" },
    { number: 607, section: "Autolinks", markdown: "<>\n", html: "<p>&lt;&gt;</p>\n" },
    { number: 608, section: "Autolinks", markdown: "< https://foo.bar >\n", html: "<p>&lt; https://foo.bar &gt;</p>\n" },
    { number: 609, section: "Autolinks", markdown: "<m:abc>\n", html: "<p>&lt;m:abc&gt;</p>\n" },
    { number: 610, section: "Autolinks", markdown: "<foo.bar.baz>\n", html: "<p>&lt;foo.bar.baz&gt;</p>\n" },
    { number: 611, section: "Autolinks", markdown: "https://example.com\n", html: "<p>https://example.com</p>\n" },
    { number: 612, section: "Autolinks", markdown: "foo@bar.example.com\n", html: "<p>foo@bar.example.com</p>\n" },
    { number: 613, section: "Raw HTML", markdown: "<a><bab><c2c>\n", html: "<p><a><bab><c2c></p>\n" },
    { number: 614, section: "Raw HTML", markdown: "<a/><b2/>\n", html: "<p><a/><b2/></p>\n" },
    { number: 615, section: "Raw HTML", markdown: "<a  /><b2\ndata=\"foo\" >\n", html: "<p><a  /><b2\ndata=\"foo\" ></p>\n" },
    { number: 616, section: "Raw HTML", markdown: "<a foo=\"bar\" bam = 'baz <em>\"</em>'\n_boolean zoop:33=zoop:33 />\n", html: "<p><a foo=\"bar\" bam = 'baz <em>\"</em>'\n_boolean zoop:33=zoop:33 /></p>\n" },
    { number: 621, section: "Raw HTML", markdown: "< a><\nfoo><bar/ >\n<foo bar=baz\nbim!bop />\n", html: "<p>&lt; a&gt;&lt;\nfoo&gt;&lt;bar/ &gt;\n&lt;foo bar=baz\nbim!bop /&gt;</p>\n" },
    { number: 623, section: "Raw HTML", markdown: "</a></foo >\n", html: "<p></a></foo ></p>\n" },
    { number: 630, section: "Raw HTML", markdown: "foo <a href=\"&ouml;\">\n", html: "<p>foo <a href=\"&ouml;\"></p>\n" },
    { number: 631, section: "Raw HTML", markdown: "foo <a href=\"\\*\">\n", html: "<p>foo <a href=\"\\*\"></p>\n" },
    { number: 632, section: "Raw HTML", markdown: "<a href=\"\\\"\">\n", html: "<p>&lt;a href=&quot;&quot;&quot;&gt;</p>\n" },
    { number: 634, section: "Hard line breaks", markdown: "foo\\\nbaz\n", html: "<p>foo<br />\nbaz</p>\n" },
    { number: 635, section: "Hard line breaks", markdown: "foo       \nbaz\n", html: "<p>foo<br />\nbaz</p>\n" },
    { number: 638, section: "Hard line breaks", markdown: "*foo  \nbar*\n", html: "<p><em>foo<br />\nbar</em></p>\n" },
    { number: 639, section: "Hard line breaks", markdown: "*foo\\\nbar*\n", html: "<p><em>foo<br />\nbar</em></p>\n" },
    { number: 640, section: "Hard line breaks", markdown: "`code  \nspan`\n", html: "<p><code>code   span</code></p>\n" },
    { number: 641, section: "Hard line breaks", markdown: "`code\\\nspan`\n", html: "<p><code>code\\ span</code></p>\n" },
    { number: 644, section: "Hard line breaks", markdown: "foo\\\n", html: "<p>foo\\</p>\n" },
    { number: 646, section: "Hard line breaks", markdown: "### foo\\\n", html: "<h3>foo\\</h3>\n" },
    { number: 647, section: "Hard line breaks", markdown: "### foo  \n", html: "<h3>foo</h3>\n" },
    { number: 651, section: "Textual content", markdown: "Foo χρῆν\n", html: "<p>Foo χρῆν</p>\n" },
    { number: 652, section: "Textual content", markdown: "Multiple     spaces\n", html: "<p>Multiple     spaces</p>\n" },
    { number: 59, section: "Thematic breaks", markdown: "Foo\n---\nbar\n", html: "<h2>Foo</h2>\n<p>bar</p>\n" },
    { number: 80, section: "Setext headings", markdown: "Foo *bar*\n=========\n\nFoo *bar*\n---------\n", html: "<h1>Foo <em>bar</em></h1>\n<h2>Foo <em>bar</em></h2>\n" },
    { number: 81, section: "Setext headings", markdown: "Foo *bar\nbaz*\n====\n", html: "<h1>Foo <em>bar\nbaz</em></h1>\n" },
    { number: 82, section: "Setext headings", markdown: "  Foo *bar\nbaz*\t\n====\n", html: "<h1>Foo <em>bar\nbaz</em></h1>\n" },
    { number: 83, section: "Setext headings", markdown: "Foo\n-------------------------\n\nFoo\n=\n", html: "<h2>Foo</h2>\n<h1>Foo</h1>\n" },
    { number: 84, section: "Setext headings", markdown: "   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===\n", html: "<h2>Foo</h2>\n<h2>Foo</h2>\n<h1>Foo</h1>\n" },
    { number: 86, section: "Setext headings", markdown: "Foo\n   ----      \n", html: "<h2>Foo</h2>\n" },
    { number: 90, section: "Setext headings", markdown: "Foo\\\n----\n", html: "<h2>Foo\\</h2>\n" },
    { number: 91, section: "Setext headings", markdown: "`Foo\n----\n`\n\n<a title=\"a lot\n---\nof dashes\"/>\n", html: "<h2>`Foo</h2>\n<p>`</p>\n<h2>&lt;a title=&quot;a lot</h2>\n<p>of dashes&quot;/&gt;</p>\n" },
    { number: 95, section: "Setext headings", markdown: "Foo\nBar\n---\n", html: "<h2>Foo\nBar</h2>\n" },
    { number: 96, section: "Setext headings", markdown: "---\nFoo\n---\nBar\n---\nBaz\n", html: "<hr />\n<h2>Foo</h2>\n<h2>Bar</h2>\n<p>Baz</p>\n" },
    { number: 102, section: "Setext headings", markdown: "\\> foo\n------\n", html: "<h2>&gt; foo</h2>\n" },
    { number: 103, section: "Setext headings", markdown: "Foo\n\nbar\n---\nbaz\n", html: "<p>Foo</p>\n<h2>bar</h2>\n<p>baz</p>\n" },
    { number: 115, section: "Indented code blocks", markdown: "# Heading\n    foo\nHeading\n------\n    foo\n----\n", html: "<h1>Heading</h1>\n<pre><code>foo\n</code></pre>\n<h2>Heading</h2>\n<pre><code>foo\n</code></pre>\n<hr />\n" },
    { number: 141, section: "Fenced code blocks", markdown: "foo\n---\n~~~\nbar\n~~~\n# baz\n", html: "<h2>foo</h2>\n<pre><code>bar\n</code></pre>\n<h1>baz</h1>\n" },
    { number: 215, section: "Link reference definitions", markdown: "[foo]: /url\nbar\n===\n[foo]\n", html: "<h1>bar</h1>\n<p><a href=\"/url\">foo</a></p>\n" },
    { number: 108, section: "Indented code blocks", markdown: "  - foo\n\n    bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n" },
    { number: 109, section: "Indented code blocks", markdown: "1.  foo\n\n    - bar\n", html: "<ol>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n" },
    { number: 254, section: "List items", markdown: "1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n" },
    { number: 258, section: "List items", markdown: " -    one\n\n      two\n", html: "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n" },
    { number: 259, section: "List items", markdown: "   > > 1.  one\n>>\n>>     two\n", html: "<blockquote>\n<blockquote>\n<ol>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ol>\n</blockquote>\n</blockquote>\n" },
    { number: 263, section: "List items", markdown: "1.  foo\n\n    ```\n    bar\n    ```\n\n    baz\n\n    > bam\n", html: "<ol>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n<blockquote>\n<p>bam</p>\n</blockquote>\n</li>\n</ol>\n" },
    { number: 266, section: "List items", markdown: "1234567890. not ok\n", html: "<p>1234567890. not ok</p>\n" },
    { number: 270, section: "List items", markdown: "- foo\n\n      bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ul>\n" },
    { number: 271, section: "List items", markdown: "  10.  foo\n\n           bar\n", html: "<ol start=\"10\">\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ol>\n" },
    { number: 273, section: "List items", markdown: "1.     indented code\n\n   paragraph\n\n       more code\n", html: "<ol>\n<li>\n<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n" },
    { number: 274, section: "List items", markdown: "1.      indented code\n\n   paragraph\n\n       more code\n", html: "<ol>\n<li>\n<pre><code> indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n" },
    { number: 286, section: "List items", markdown: " 1.  A paragraph\n     with two lines.\n\n         indented code\n\n     > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n" },
    { number: 287, section: "List items", markdown: "  1.  A paragraph\n      with two lines.\n\n          indented code\n\n      > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n" },
    { number: 288, section: "List items", markdown: "   1.  A paragraph\n       with two lines.\n\n           indented code\n\n       > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n" },
    { number: 290, section: "List items", markdown: "  1.  A paragraph\nwith two lines.\n\n          indented code\n\n      > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n" },
    { number: 304, section: "Lists", markdown: "The number of windows in my house is\n14.  The number of doors is 6.\n", html: "<p>The number of windows in my house is\n14.  The number of doors is 6.</p>\n" },
    { number: 309, section: "Lists", markdown: "-   foo\n\n    notcode\n\n-   foo\n\n<!-- -->\n\n    code\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>notcode</p>\n</li>\n<li>\n<p>foo</p>\n</li>\n</ul>\n<!-- -->\n<pre><code>code\n</code></pre>\n" },
    { number: 325, section: "Lists", markdown: "* foo\n  * bar\n\n  baz\n", html: "<ul>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n<p>baz</p>\n</li>\n</ul>\n" },
    { number: 326, section: "Lists", markdown: "- a\n  - b\n  - c\n\n- d\n  - e\n  - f\n", html: "<ul>\n<li>\n<p>a</p>\n<ul>\n<li>b</li>\n<li>c</li>\n</ul>\n</li>\n<li>\n<p>d</p>\n<ul>\n<li>e</li>\n<li>f</li>\n</ul>\n</li>\n</ul>\n" },
    { number: 56, section: "Thematic breaks", markdown: " *-*\n", html: "<p><em>-</em></p>\n" },
    { number: 222, section: "Paragraphs", markdown: "  aaa\n bbb\n", html: "<p>aaa\nbbb</p>\n" },
    { number: 224, section: "Paragraphs", markdown: "   aaa\nbbb\n", html: "<p>aaa\nbbb</p>\n" },
    { number: 255, section: "List items", markdown: "- one\n\n two\n", html: "<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n" },
    { number: 262, section: "List items", markdown: "- foo\n\n\n  bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n" },
    { number: 264, section: "List items", markdown: "- Foo\n\n      bar\n\n\n      baz\n", html: "<ul>\n<li>\n<p>Foo</p>\n<pre><code>bar\n\n\nbaz\n</code></pre>\n</li>\n</ul>\n" },
    { number: 267, section: "List items", markdown: "0. ok\n", html: "<ol start=\"0\">\n<li>ok</li>\n</ol>\n" },
    { number: 275, section: "List items", markdown: "   foo\n\nbar\n", html: "<p>foo</p>\n<p>bar</p>\n" },
    { number: 276, section: "List items", markdown: "-    foo\n\n  bar\n", html: "<ul>\n<li>foo</li>\n</ul>\n<p>bar</p>\n" },
    { number: 552, section: "Links", markdown: "[\n ]\n\n[\n ]: /uri\n", html: "<p>[\n]</p>\n<p>[\n]: /uri</p>\n" },
    { number: 128, section: "Fenced code blocks", markdown: "> ```\n> aaa\n\nbbb\n", html: "<blockquote>\n<pre><code>aaa\n</code></pre>\n</blockquote>\n<p>bbb</p>\n" },
    { number: 232, section: "Block quotes", markdown: "> # Foo\n> bar\nbaz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n" },
    { number: 233, section: "Block quotes", markdown: "> bar\nbaz\n> foo\n", html: "<blockquote>\n<p>bar\nbaz\nfoo</p>\n</blockquote>\n" },
    { number: 242, section: "Block quotes", markdown: "> foo\n\n> bar\n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n<blockquote>\n<p>bar</p>\n</blockquote>\n" },
    { number: 247, section: "Block quotes", markdown: "> bar\nbaz\n", html: "<blockquote>\n<p>bar\nbaz</p>\n</blockquote>\n" },
    { number: 252, section: "Block quotes", markdown: ">     code\n\n>    not code\n", html: "<blockquote>\n<pre><code>code\n</code></pre>\n</blockquote>\n<blockquote>\n<p>not code</p>\n</blockquote>\n" },
    { number: 485, section: "Links", markdown: "[link]()\n", html: "<p><a href=\"\">link</a></p>\n" },
    { number: 486, section: "Links", markdown: "[link](<>)\n", html: "<p><a href=\"\">link</a></p>\n" },
    { number: 487, section: "Links", markdown: "[]()\n", html: "<p><a href=\"\"></a></p>\n" },
    { number: 567, section: "Links", markdown: "[foo]()\n\n[foo]: /url1\n", html: "<p><a href=\"\">foo</a></p>\n" },
    { number: 579, section: "Images", markdown: "My ![foo bar](/path/to/train.jpg  \"title\"   )\n", html: "<p>My <img src=\"/path/to/train.jpg\" alt=\"foo bar\" title=\"title\" /></p>\n" },
    { number: 580, section: "Images", markdown: "![foo](<url>)\n", html: "<p><img src=\"url\" alt=\"foo\" /></p>\n" },
    { number: 48, section: "Thematic breaks", markdown: "    ***\n", html: "<pre><code>***\n</code></pre>\n" },
    { number: 49, section: "Thematic breaks", markdown: "Foo\n    ***\n", html: "<p>Foo\n***</p>\n" },
    { number: 70, section: "ATX headings", markdown: "foo\n    # bar\n", html: "<p>foo\n# bar</p>\n" },
    { number: 75, section: "ATX headings", markdown: "# foo#\n", html: "<h1>foo#</h1>\n" },
    { number: 76, section: "ATX headings", markdown: "### foo \\###\n## foo #\\##\n# foo \\#\n", html: "<h3>foo ###</h3>\n<h2>foo ###</h2>\n<h1>foo #</h1>\n" },
    { number: 87, section: "Setext headings", markdown: "Foo\n    ---\n", html: "<p>Foo\n---</p>\n" },
    { number: 113, section: "Indented code blocks", markdown: "Foo\n    bar\n\n", html: "<p>Foo\nbar</p>\n" },
    { number: 223, section: "Paragraphs", markdown: "aaa\n             bbb\n                                       ccc\n", html: "<p>aaa\nbbb\nccc</p>\n" },
    { number: 238, section: "Block quotes", markdown: "> foo\n    - bar\n", html: "<blockquote>\n<p>foo\n- bar</p>\n</blockquote>\n" },
    { number: 636, section: "Hard line breaks", markdown: "foo  \n     bar\n", html: "<p>foo<br />\nbar</p>\n" },
    { number: 637, section: "Hard line breaks", markdown: "foo\\\n     bar\n", html: "<p>foo<br />\nbar</p>\n" },
    { number: 12, section: "Backslash escapes", markdown: "\\!\\\"\\#\\$\\%\\&\\'\\(\\)\\*\\+\\,\\-\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\\\\\]\\^\\_\\`\\{\\|\\}\\~\n", html: "<p>!&quot;\#$%&amp;'()*+,-./:;&lt;=&gt;?@[\\]^_`{|}~</p>\n" },
    { number: 620, section: "Raw HTML", markdown: "<a href=\"hi'> <a href=hi'>\n", html: "<p>&lt;a href=&quot;hi'&gt; &lt;a href=hi'&gt;</p>\n" },
    { number: 622, section: "Raw HTML", markdown: "<a href='bar'title=title>\n", html: "<p>&lt;a href='bar'title=title&gt;</p>\n" },
    { number: 645, section: "Hard line breaks", markdown: "foo  \n", html: "<p>foo</p>\n" },
    { number: 650, section: "Textual content", markdown: "hello $.;'there\n", html: "<p>hello $.;'there</p>\n" },
    { number: 131, section: "Fenced code blocks", markdown: " ```\n aaa\naaa\n```\n", html: "<pre><code>aaa\naaa\n</code></pre>\n" },
    { number: 132, section: "Fenced code blocks", markdown: "  ```\naaa\n  aaa\naaa\n  ```\n", html: "<pre><code>aaa\naaa\naaa\n</code></pre>\n" },
    { number: 133, section: "Fenced code blocks", markdown: "   ```\n   aaa\n    aaa\n  aaa\n   ```\n", html: "<pre><code>aaa\n aaa\naaa\n</code></pre>\n" },
    { number: 138, section: "Fenced code blocks", markdown: "``` ```\naaa\n", html: "<p><code> </code>\naaa</p>\n" },
    { number: 145, section: "Fenced code blocks", markdown: "``` aa ```\nfoo\n", html: "<p><code>aa</code>\nfoo</p>\n" },
    { number: 338, section: "Code spans", markdown: "`foo\\`bar`\n", html: "<p><code>foo\\</code>bar`</p>\n" },
    { number: 347, section: "Code spans", markdown: "```foo``\n", html: "<p>```foo``</p>\n" },
    { number: 279, section: "List items", markdown: "-   \n  foo\n", html: "<ul>\n<li>foo</li>\n</ul>\n" },
    { number: 280, section: "List items", markdown: "-\n\n  foo\n", html: "<ul>\n<li></li>\n</ul>\n<p>foo</p>\n" },
    { number: 281, section: "List items", markdown: "- foo\n-\n- bar\n", html: "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n" },
    { number: 282, section: "List items", markdown: "- foo\n-   \n- bar\n", html: "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n" },
    { number: 283, section: "List items", markdown: "1. foo\n2.\n3. bar\n", html: "<ol>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ol>\n" },
    { number: 284, section: "List items", markdown: "*\n", html: "<ul>\n<li></li>\n</ul>\n" },
    { number: 294, section: "List items", markdown: "- foo\n  - bar\n    - baz\n      - boo\n", html: "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz\n<ul>\n<li>boo</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n" },
    { number: 296, section: "List items", markdown: "10) foo\n    - bar\n", html: "<ol start=\"10\">\n<li>foo\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n" },
    { number: 320, section: "Lists", markdown: "* a\n  > b\n  >\n* c\n", html: "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n</li>\n<li>c</li>\n</ul>\n" },
    { number: 323, section: "Lists", markdown: "- a\n  - b\n", html: "<ul>\n<li>a\n<ul>\n<li>b</li>\n</ul>\n</li>\n</ul>\n" },
    { number: 411, section: "Emphasis and strong emphasis", markdown: "*foo**bar**baz*\n", html: "<p><em>foo<strong>bar</strong>baz</em></p>\n" },
    { number: 412, section: "Emphasis and strong emphasis", markdown: "*foo**bar*\n", html: "<p><em>foo**bar</em></p>\n" },
    { number: 415, section: "Emphasis and strong emphasis", markdown: "*foo**bar***\n", html: "<p><em>foo<strong>bar</strong></em></p>\n" },
    { number: 429, section: "Emphasis and strong emphasis", markdown: "**foo*bar*baz**\n", html: "<p><strong>foo<em>bar</em>baz</strong></p>\n" },
    { number: 22, section: "Backslash escapes", markdown: "[foo](/bar\\* \"ti\\*tle\")\n", html: "<p><a href=\"/bar*\" title=\"ti*tle\">foo</a></p>\n" },
    { number: 41, section: "Entity and numeric character references", markdown: "[a](url &quot;tit&quot;)\n", html: "<p>[a](url &quot;tit&quot;)</p>\n" },
    { number: 488, section: "Links", markdown: "[link](/my uri)\n", html: "<p>[link](/my uri)</p>\n" },
    { number: 489, section: "Links", markdown: "[link](</my uri>)\n", html: "<p><a href=\"/my%20uri\">link</a></p>\n" },
    { number: 492, section: "Links", markdown: "[a](<b)c>)\n", html: "<p><a href=\"b)c\">a</a></p>\n" },
    { number: 493, section: "Links", markdown: "[link](<foo\\>)\n", html: "<p>[link](&lt;foo&gt;)</p>\n" },
    { number: 494, section: "Links", markdown: "[a](<b)c\n[a](<b)c>\n[a](<b>c)\n", html: "<p>[a](&lt;b)c\n[a](&lt;b)c&gt;\n[a](<b>c)</p>\n" },
    { number: 495, section: "Links", markdown: "[link](\\(foo\\))\n", html: "<p><a href=\"(foo)\">link</a></p>\n" },
    { number: 498, section: "Links", markdown: "[link](foo\\(and\\(bar\\))\n", html: "<p><a href=\"foo(and(bar)\">link</a></p>\n" },
    { number: 499, section: "Links", markdown: "[link](<foo(and(bar)>)\n", html: "<p><a href=\"foo(and(bar)\">link</a></p>\n" },
    { number: 500, section: "Links", markdown: "[link](foo\\)\\:)\n", html: "<p><a href=\"foo):\">link</a></p>\n" },
    { number: 502, section: "Links", markdown: "[link](foo\\bar)\n", html: "<p><a href=\"foo%5Cbar\">link</a></p>\n" },
    { number: 504, section: "Links", markdown: "[link](\"title\")\n", html: "<p><a href=\"%22title%22\">link</a></p>\n" },
    { number: 505, section: "Links", markdown: "[link](/url \"title\")\n[link](/url 'title')\n[link](/url (title))\n", html: "<p><a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a>\n<a href=\"/url\" title=\"title\">link</a></p>\n" },
    { number: 506, section: "Links", markdown: "[link](/url \"title \\\"&quot;\")\n", html: "<p><a href=\"/url\" title=\"title &quot;&quot;\">link</a></p>\n" },
    { number: 507, section: "Links", markdown: "[link](/url \"title\")\n", html: "<p><a href=\"/url%C2%A0%22title%22\">link</a></p>\n" },
    { number: 508, section: "Links", markdown: "[link](/url \"title \"and\" title\")\n", html: "<p>[link](/url &quot;title &quot;and&quot; title&quot;)</p>\n" },
    { number: 509, section: "Links", markdown: "[link](/url 'title \"and\" title')\n", html: "<p><a href=\"/url\" title=\"title &quot;and&quot; title\">link</a></p>\n" },
    { number: 510, section: "Links", markdown: "[link](   /uri\n  \"title\"  )\n", html: "<p><a href=\"/uri\" title=\"title\">link</a></p>\n" },
    { number: 568, section: "Links", markdown: "[foo](not a link)\n\n[foo]: /url1\n", html: "<p><a href=\"/url1\">foo</a>(not a link)</p>\n" },
    { number: 23, section: "Backslash escapes", markdown: "[foo]\n\n[foo]: /bar\\* \"ti\\*tle\"\n", html: "<p><a href=\"/bar*\" title=\"ti*tle\">foo</a></p>\n" },
    { number: 24, section: "Backslash escapes", markdown: "``` foo\\+bar\nfoo\n```\n", html: "<pre><code class=\"language-foo+bar\">foo\n</code></pre>\n" },
    { number: 79, section: "ATX headings", markdown: "## \n#\n### ###\n", html: "<h2></h2>\n<h1></h1>\n<h3></h3>\n" },
    { number: 112, section: "Indented code blocks", markdown: "    chunk1\n      \n      chunk2\n", html: "<pre><code>chunk1\n  \n  chunk2\n</code></pre>\n" },
    { number: 117, section: "Indented code blocks", markdown: "\n    \n    foo\n    \n\n", html: "<pre><code>foo\n</code></pre>\n" },
    { number: 354, section: "Emphasis and strong emphasis", markdown: "*$*alpha.\n\n*£*bravo.\n\n*€*charlie.\n", html: "<p>*$*alpha.</p>\n<p>*£*bravo.</p>\n<p>*€*charlie.</p>\n" },
    { number: 556, section: "Links", markdown: "[foo] \n[]\n\n[foo]: /url \"title\"\n", html: "<p><a href=\"/url\" title=\"title\">foo</a>\n[]</p>\n" },
    { number: 587, section: "Images", markdown: "![foo] \n[]\n\n[foo]: /url \"title\"\n", html: "<p><img src=\"/url\" alt=\"foo\" title=\"title\" />\n[]</p>\n" },
    { number: 649, section: "Soft line breaks", markdown: "foo \n baz\n", html: "<p>foo\nbaz</p>\n" },
    { number: 61, section: "Thematic breaks", markdown: "- Foo\n- * * *\n", html: "<ul>\n<li>Foo</li>\n<li>\n<hr />\n</li>\n</ul>\n" },
    { number: 175, section: "HTML blocks", markdown: "- <div>\n- foo\n", html: "<ul>\n<li>\n<div>\n</li>\n<li>foo</li>\n</ul>\n" },
    { number: 278, section: "List items", markdown: "-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz\n", html: "<ul>\n<li>foo</li>\n<li>\n<pre><code>bar\n</code></pre>\n</li>\n<li>\n<pre><code>baz\n</code></pre>\n</li>\n</ul>\n" },
    { number: 293, section: "List items", markdown: "> 1. > Blockquote\n> continued here.\n", html: "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n" },
    { number: 298, section: "List items", markdown: "- - foo\n", html: "<ul>\n<li>\n<ul>\n<li>foo</li>\n</ul>\n</li>\n</ul>\n" },
    { number: 299, section: "List items", markdown: "1. - 2. foo\n", html: "<ol>\n<li>\n<ul>\n<li>\n<ol start=\"2\">\n<li>foo</li>\n</ol>\n</li>\n</ul>\n</li>\n</ol>\n" },
    { number: 315, section: "Lists", markdown: "* a\n*\n\n* c\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li></li>\n<li>\n<p>c</p>\n</li>\n</ul>\n" },
    { number: 153, section: "HTML blocks", markdown: "<div id=\"foo\"\n  class=\"bar\">\n</div>\n", html: "<div id=\"foo\"\n  class=\"bar\">\n</div>\n" },
    { number: 154, section: "HTML blocks", markdown: "<div id=\"foo\" class=\"bar\n  baz\">\n</div>\n", html: "<div id=\"foo\" class=\"bar\n  baz\">\n</div>\n" },
    { number: 156, section: "HTML blocks", markdown: "<div id=\"foo\"\n*hi*\n", html: "<div id=\"foo\"\n*hi*\n" },
    { number: 157, section: "HTML blocks", markdown: "<div class\nfoo\n", html: "<div class\nfoo\n" },
    { number: 158, section: "HTML blocks", markdown: "<div *???-&&&-<---\n*foo*\n", html: "<div *???-&&&-<---\n*foo*\n" },
    { number: 160, section: "HTML blocks", markdown: "<table><tr><td>\nfoo\n</td></tr></table>\n", html: "<table><tr><td>\nfoo\n</td></tr></table>\n" },
    { number: 168, section: "HTML blocks", markdown: "<del>*foo*</del>\n", html: "<p><del><em>foo</em></del></p>\n" },
    { number: 624, section: "Raw HTML", markdown: "</a href=\"foo\">\n", html: "<p>&lt;/a href=&quot;foo&quot;&gt;</p>\n" },
    { number: 625, section: "Raw HTML", markdown: "foo <!-- this is a --\ncomment - with hyphens -->\n", html: "<p>foo <!-- this is a --\ncomment - with hyphens --></p>\n" },
    { number: 626, section: "Raw HTML", markdown: "foo <!--> foo -->\n\nfoo <!---> foo -->\n", html: "<p>foo <!--> foo --&gt;</p>\n<p>foo <!---> foo --&gt;</p>\n" },
    { number: 627, section: "Raw HTML", markdown: "foo <?php echo $a; ?>\n", html: "<p>foo <?php echo $a; ?></p>\n" },
    { number: 628, section: "Raw HTML", markdown: "foo <!ELEMENT br EMPTY>\n", html: "<p>foo <!ELEMENT br EMPTY></p>\n" },
    { number: 629, section: "Raw HTML", markdown: "foo <![CDATA[>&<]]>\n", html: "<p>foo <![CDATA[>&<]]></p>\n" },
    { number: 642, section: "Hard line breaks", markdown: "<a href=\"foo  \nbar\">\n", html: "<p><a href=\"foo  \nbar\"></p>\n" },
    { number: 643, section: "Hard line breaks", markdown: "<a href=\"foo\\\nbar\">\n", html: "<p><a href=\"foo\\\nbar\"></p>\n" },
    { number: 20, section: "Backslash escapes", markdown: "<https://example.com?find=\\*>\n", html: "<p><a href=\"https://example.com?find=%5C*\">https://example.com?find=\\*</a></p>\n" },
    { number: 343, section: "Code spans", markdown: "`<a href=\"`\">`\n", html: "<p><code>&lt;a href=&quot;</code>&quot;&gt;`</p>\n" },
    { number: 345, section: "Code spans", markdown: "`<https://foo.bar.`baz>`\n", html: "<p><code>&lt;https://foo.bar.</code>baz&gt;`</p>\n" },
    { number: 346, section: "Code spans", markdown: "<https://foo.bar.`baz>`\n", html: "<p><a href=\"https://foo.bar.%60baz\">https://foo.bar.`baz</a>`</p>\n" },
    { number: 526, section: "Links", markdown: "[foo<https://example.com/?search=](uri)>\n", html: "<p>[foo<a href=\"https://example.com/?search=%5D(uri)\">https://example.com/?search=](uri)</a></p>\n" },
    { number: 538, section: "Links", markdown: "[foo<https://example.com/?search=][ref]>\n\n[ref]: /uri\n", html: "<p>[foo<a href=\"https://example.com/?search=%5D%5Bref%5D\">https://example.com/?search=][ref]</a></p>\n" },
    { number: 603, section: "Autolinks", markdown: "<https://example.com/\\[\\>\n", html: "<p><a href=\"https://example.com/%5C%5B%5C\">https://example.com/\\[\\</a></p>\n" },
    { number: 25, section: "Entity and numeric character references", markdown: "&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;\n", html: "<p>  &amp; © Æ Ď\n¾ ℋ ⅆ\n∲ ≧̸</p>\n" },
    { number: 32, section: "Entity and numeric character references", markdown: "[foo](/f&ouml;&ouml; \"f&ouml;&ouml;\")\n", html: "<p><a href=\"/f%C3%B6%C3%B6\" title=\"föö\">foo</a></p>\n" },
    { number: 34, section: "Entity and numeric character references", markdown: "``` f&ouml;&ouml;\nfoo\n```\n", html: "<pre><code class=\"language-föö\">foo\n</code></pre>\n" },
    { number: 60, section: "Thematic breaks", markdown: "* Foo\n* * *\n* Bar\n", html: "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n<ul>\n<li>Bar</li>\n</ul>\n" },
    { number: 93, section: "Setext headings", markdown: "> foo\nbar\n===\n", html: "<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>\n" },
    { number: 503, section: "Links", markdown: "[link](foo%20b&auml;)\n", html: "<p><a href=\"foo%20b%C3%A4\">link</a></p>\n" },
    { number: 33, section: "Entity and numeric character references", markdown: "[foo]\n\n[foo]: /f&ouml;&ouml; \"f&ouml;&ouml;\"\n", html: "<p><a href=\"/f%C3%B6%C3%B6\" title=\"föö\">foo</a></p>\n" },
    { number: 195, section: "Link reference definitions", markdown: "[Foo bar]:\n<my url>\n'title'\n\n[Foo bar]\n", html: "<p><a href=\"my%20url\" title=\"title\">Foo bar</a></p>\n" },
    { number: 202, section: "Link reference definitions", markdown: "[foo]: /url\\bar\\*baz \"foo\\\"bar\\baz\"\n\n[foo]\n", html: "<p><a href=\"/url%5Cbar*baz\" title=\"foo&quot;bar\\baz\">foo</a></p>\n" },
    { number: 182, section: "HTML blocks", markdown: "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\nokay\n", html: "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\n<p>okay</p>\n" },
    { number: 194, section: "Link reference definitions", markdown: "[Foo*bar\\]]:my_(url) 'title (with parens)'\n\n[Foo*bar\\]]\n", html: "<p><a href=\"my_(url)\" title=\"title (with parens)\">Foo*bar]</a></p>\n" },
    { number: 201, section: "Link reference definitions", markdown: "[foo]: <bar>(baz)\n\n[foo]\n", html: "<p>[foo]: <bar>(baz)</p>\n<p>[foo]</p>\n" },
    { number: 187, section: "HTML blocks", markdown: "Foo\n<a href=\"bar\">\nbaz\n", html: "<p>Foo\n<a href=\"bar\">\nbaz</p>\n" },
    { number: 321, section: "Lists", markdown: "- a\n  > b\n  ```\n  c\n  ```\n- d\n", html: "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n<pre><code>c\n</code></pre>\n</li>\n<li>d</li>\n</ul>\n" },
    { number: 318, section: "Lists", markdown: "- a\n- ```\n  b\n\n\n  ```\n- c\n", html: "<ul>\n<li>a</li>\n<li>\n<pre><code>b\n\n\n</code></pre>\n</li>\n<li>c</li>\n</ul>\n" },
    { number: 1, section: "Tabs", markdown: "\tfoo\tbaz\t\tbim\n", html: "<pre><code>foo\tbaz\t\tbim\n</code></pre>\n" },
    { number: 2, section: "Tabs", markdown: "  \tfoo\tbaz\t\tbim\n", html: "<pre><code>foo\tbaz\t\tbim\n</code></pre>\n" },
    { number: 4, section: "Tabs", markdown: "  - foo\n\n\tbar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n" },
    { number: 5, section: "Tabs", markdown: "- foo\n\n\t\tbar\n", html: "<ul>\n<li>\n<p>foo</p>\n<pre><code>  bar\n</code></pre>\n</li>\n</ul>\n" },
    { number: 6, section: "Tabs", markdown: ">\t\tfoo\n", html: "<blockquote>\n<pre><code>  foo\n</code></pre>\n</blockquote>\n" },
    { number: 7, section: "Tabs", markdown: "-\t\tfoo\n", html: "<ul>\n<li>\n<pre><code>  foo\n</code></pre>\n</li>\n</ul>\n" },
    { number: 8, section: "Tabs", markdown: "    foo\n\tbar\n", html: "<pre><code>foo\nbar\n</code></pre>\n" },
    { number: 9, section: "Tabs", markdown: " - foo\n   - bar\n\t - baz\n", html: "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n" },
    { number: 540, section: "Links", markdown: "[ẞ]\n\n[SS]: /url\n", html: "<p><a href=\"/url\">ẞ</a></p>\n" },
    { number: 300, section: "List items", markdown: "- # Foo\n- Bar\n  ---\n  baz\n", html: "<ul>\n<li>\n<h1>Foo</h1>\n</li>\n<li>\n<h2>Bar</h2>\nbaz</li>\n</ul>\n" },
    { number: 312, section: "Lists", markdown: "- a\n - b\n  - c\n   - d\n    - e\n", html: "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d\n- e</li>\n</ul>\n" },
    { number: 546, section: "Links", markdown: "[foo][ref[]\n\n[ref[]: /uri\n", html: "<p>[foo][ref[]</p>\n<p>[ref[]: /uri</p>\n" },
    { number: 210, section: "Link reference definitions", markdown: "[foo]: /url\n\"title\" ok\n", html: "<p>&quot;title&quot; ok</p>\n" },
    { number: 250, section: "Block quotes", markdown: "> > > foo\nbar\n", html: "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n</blockquote>\n</blockquote>\n" },
    { number: 251, section: "Block quotes", markdown: ">>> foo\n> bar\n>>baz\n", html: "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar\nbaz</p>\n</blockquote>\n</blockquote>\n</blockquote>\n" },
    { number: 292, section: "List items", markdown: "> 1. > Blockquote\ncontinued here.\n", html: "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n" },
  ].freeze

  KNOWN_GAPS = [].freeze

  PASSING_EXAMPLES.each do |example|
    it "matches CommonMark 0.31.2 example #{example[:number]} (#{example[:section]})" do
      doc = Mdarena.parse(example[:markdown], allow_html: true)
      expect { doc.arena.check_integrity!(doc.root_id) }.not_to raise_error
      expect(doc.to_html).to eq(example[:html])
    end
  end

  KNOWN_GAPS.each do |example|
    it "does not yet match CommonMark 0.31.2 example #{example[:number]} (#{example[:section]})" do
      pending(example[:reason])
      expect(Mdarena.render_html(example[:markdown], allow_html: true)).to eq(example[:html])
    end
  end
end
